### ISSUE TITLE
error. /home/lucio/opt/Espanso.AppImage: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full

### ISSUE THREAD

**Issue by Luciofulci** [espanso/espanso#900] opened 2021-12-06 16:58 UTC
Hi, man. I'm trying to install the new alpha version, but I get this error. /home/lucio/opt/Espanso.AppImage: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full

(this error generates in the step sudo ~/opt/Espanso.AppImage env-path register )

I have confirmed with echo $XDG_SESSION_TYPE that I'm running X11 over Manjaro Gnome.

Thanks a lot!

**Comment by federico-terzi** [comment] 2021-12-06 21:17
Hey @Luciofulci,

Thanks for reporting this issue! As soon as I get my hands on a Linux machine, I'll investigate :)

Cheers :)

**Comment by federico-terzi** [comment] 2021-12-11 17:26
@Luciofulci When you have the chance, could you please retry with this AppImage? You can find it under the "Artifacts" section: https://github.com/federico-terzi/espanso/actions/runs/1567438928

Following these instructions: https://espanso.org/docs/next/install/linux/#installing-with-appimage

Let me know if that helps :)

**Comment by Luciofulci** [comment] 2021-12-14 14:52
@federico-terzi Hi. It gaves me the same error in the third step (sudo ~/opt/Espanso-X11.AppImage env-path register) :( 

/home/lucio/opt/Espanso-X11.AppImage: symbol lookup error: /usr/lib/libgobject-2.0.so.0: undefined symbol: g_atomic_rc_box_release_full

**Comment by federico-terzi** [comment] 2021-12-16 20:21
@Luciofulci Thanks! It seems the AppImage is missing quite a few libraries...

When you have the chance, could you please run these commands

```
/home/lucio/opt/Espanso-X11.AppImage --appimage-extract
ldd /home/lucio/opt/squashfs-root/usr/bin/espanso
```

and post the output here? 

Cheers :)

**Comment by Luciofulci** [comment] 2021-12-16 22:13
This is the output. Thanks for the help!

squashfs-root/.DirIcon
squashfs-root/AppRun
squashfs-root/espanso.desktop
squashfs-root/icon.png
squashfs-root/usr
squashfs-root/usr/bin
squashfs-root/usr/bin/espanso
squashfs-root/usr/lib
squashfs-root/usr/lib/libXau.so.6
squashfs-root/usr/lib/libXcomposite.so.1
squashfs-root/usr/lib/libXcursor.so.1
squashfs-root/usr/lib/libXdamage.so.1
squashfs-root/usr/lib/libXdmcp.so.6
squashfs-root/usr/lib/libXext.so.6
squashfs-root/usr/lib/libXfixes.so.3
squashfs-root/usr/lib/libXi.so.6
squashfs-root/usr/lib/libXinerama.so.1
squashfs-root/usr/lib/libXrandr.so.2
squashfs-root/usr/lib/libXrender.so.1
squashfs-root/usr/lib/libXtst.so.6
squashfs-root/usr/lib/libXxf86vm.so.1
squashfs-root/usr/lib/libatk-1.0.so.0
squashfs-root/usr/lib/libatk-bridge-2.0.so.0
squashfs-root/usr/lib/libatspi.so.0
squashfs-root/usr/lib/libblkid.so.1
squashfs-root/usr/lib/libbsd.so.0
squashfs-root/usr/lib/libcairo-gobject.so.2
squashfs-root/usr/lib/libcairo.so.2
squashfs-root/usr/lib/libcrypto.so.1.1
squashfs-root/usr/lib/libdatrie.so.1
squashfs-root/usr/lib/libdbus-1.so.3
squashfs-root/usr/lib/libepoxy.so.0
squashfs-root/usr/lib/libffi.so.6
squashfs-root/usr/lib/libgcrypt.so.20
squashfs-root/usr/lib/libgdk-3.so.0
squashfs-root/usr/lib/libgdk_pixbuf-2.0.so.0
squashfs-root/usr/lib/libglib-2.0.so.0
squashfs-root/usr/lib/libgmodule-2.0.so.0
squashfs-root/usr/lib/libgraphite2.so.3
squashfs-root/usr/lib/libgtk-3.so.0
squashfs-root/usr/lib/libjbig.so.0
squashfs-root/usr/lib/libjpeg.so.8
squashfs-root/usr/lib/liblz4.so.1
squashfs-root/usr/lib/liblzma.so.5
squashfs-root/usr/lib/libmount.so.1
squashfs-root/usr/lib/libnotify.so.4
squashfs-root/usr/lib/libpcre.so.3
squashfs-root/usr/lib/libpixman-1.so.0
squashfs-root/usr/lib/libpng16.so.16
squashfs-root/usr/lib/libselinux.so.1
squashfs-root/usr/lib/libssl.so.1.1
squashfs-root/usr/lib/libsystemd.so.0
squashfs-root/usr/lib/libtiff.so.5
squashfs-root/usr/lib/libwayland-client.so.0
squashfs-root/usr/lib/libwayland-cursor.so.0
squashfs-root/usr/lib/libwayland-egl.so.1
squashfs-root/usr/lib/libwx_baseu-3.0.so.0
squashfs-root/usr/lib/libwx_gtk3u_adv-3.0.so.0
squashfs-root/usr/lib/libwx_gtk3u_core-3.0.so.0
squashfs-root/usr/lib/libwx_gtk3u_html-3.0.so.0
squashfs-root/usr/lib/libxcb-render.so.0
squashfs-root/usr/lib/libxcb-shm.so.0
squashfs-root/usr/lib/libxkbcommon.so.0
squashfs-root/usr/share
squashfs-root/usr/share/applications
squashfs-root/usr/share/applications/espanso.desktop
squashfs-root/usr/share/doc
squashfs-root/usr/share/doc/libatk-bridge2.0-0
squashfs-root/usr/share/doc/libatk-bridge2.0-0/copyright
squashfs-root/usr/share/doc/libatk1.0-0
squashfs-root/usr/share/doc/libatk1.0-0/copyright
squashfs-root/usr/share/doc/libatspi2.0-0
squashfs-root/usr/share/doc/libatspi2.0-0/copyright
squashfs-root/usr/share/doc/libblkid1
squashfs-root/usr/share/doc/libblkid1/copyright
squashfs-root/usr/share/doc/libbsd0
squashfs-root/usr/share/doc/libbsd0/copyright
squashfs-root/usr/share/doc/libcairo-gobject2
squashfs-root/usr/share/doc/libcairo-gobject2/copyright
squashfs-root/usr/share/doc/libcairo2
squashfs-root/usr/share/doc/libcairo2/copyright
squashfs-root/usr/share/doc/libdatrie1
squashfs-root/usr/share/doc/libdatrie1/copyright
squashfs-root/usr/share/doc/libdbus-1-3
squashfs-root/usr/share/doc/libdbus-1-3/copyright
squashfs-root/usr/share/doc/libepoxy0
squashfs-root/usr/share/doc/libepoxy0/copyright
squashfs-root/usr/share/doc/libffi6
squashfs-root/usr/share/doc/libffi6/copyright
squashfs-root/usr/share/doc/libgcrypt20
squashfs-root/usr/share/doc/libgcrypt20/copyright
squashfs-root/usr/share/doc/libgdk-pixbuf2.0-0
squashfs-root/usr/share/doc/libgdk-pixbuf2.0-0/copyright
squashfs-root/usr/share/doc/libglib2.0-0
squashfs-root/usr/share/doc/libglib2.0-0/copyright
squashfs-root/usr/share/doc/libgraphite2-3
squashfs-root/usr/share/doc/libgraphite2-3/copyright
squashfs-root/usr/share/doc/libgtk-3-0
squashfs-root/usr/share/doc/libgtk-3-0/copyright
squashfs-root/usr/share/doc/libjbig0
squashfs-root/usr/share/doc/libjbig0/copyright
squashfs-root/usr/share/doc/libjpeg-turbo8
squashfs-root/usr/share/doc/libjpeg-turbo8/copyright
squashfs-root/usr/share/doc/liblz4-1
squashfs-root/usr/share/doc/liblz4-1/copyright
squashfs-root/usr/share/doc/liblzma5
squashfs-root/usr/share/doc/liblzma5/copyright
squashfs-root/usr/share/doc/libmount1
squashfs-root/usr/share/doc/libmount1/copyright
squashfs-root/usr/share/doc/libnotify4
squashfs-root/usr/share/doc/libnotify4/copyright
squashfs-root/usr/share/doc/libpcre3
squashfs-root/usr/share/doc/libpcre3/copyright
squashfs-root/usr/share/doc/libpixman-1-0
squashfs-root/usr/share/doc/libpixman-1-0/copyright
squashfs-root/usr/share/doc/libpng16-16
squashfs-root/usr/share/doc/libpng16-16/copyright
squashfs-root/usr/share/doc/libselinux1
squashfs-root/usr/share/doc/libselinux1/copyright
squashfs-root/usr/share/doc/libssl1.1
squashfs-root/usr/share/doc/libssl1.1/copyright
squashfs-root/usr/share/doc/libsystemd0
squashfs-root/usr/share/doc/libsystemd0/copyright
squashfs-root/usr/share/doc/libtiff5
squashfs-root/usr/share/doc/libtiff5/copyright
squashfs-root/usr/share/doc/libwayland-client0
squashfs-root/usr/share/doc/libwayland-client0/copyright
squashfs-root/usr/share/doc/libwayland-cursor0
squashfs-root/usr/share/doc/libwayland-cursor0/copyright
squashfs-root/usr/share/doc/libwayland-egl1
squashfs-root/usr/share/doc/libwayland-egl1/copyright
squashfs-root/usr/share/doc/libwxbase3.0-0v5
squashfs-root/usr/share/doc/libwxbase3.0-0v5/copyright
squashfs-root/usr/share/doc/libwxgtk3.0-gtk3-0v5
squashfs-root/usr/share/doc/libwxgtk3.0-gtk3-0v5/copyright
squashfs-root/usr/share/doc/libxau6
squashfs-root/usr/share/doc/libxau6/copyright
squashfs-root/usr/share/doc/libxcb-render0
squashfs-root/usr/share/doc/libxcb-render0/copyright
squashfs-root/usr/share/doc/libxcb-shm0
squashfs-root/usr/share/doc/libxcb-shm0/copyright
squashfs-root/usr/share/doc/libxcomposite1
squashfs-root/usr/share/doc/libxcomposite1/copyright
squashfs-root/usr/share/doc/libxcursor1
squashfs-root/usr/share/doc/libxcursor1/copyright
squashfs-root/usr/share/doc/libxdamage1
squashfs-root/usr/share/doc/libxdamage1/copyright
squashfs-root/usr/share/doc/libxdmcp6
squashfs-root/usr/share/doc/libxdmcp6/copyright
squashfs-root/usr/share/doc/libxext6
squashfs-root/usr/share/doc/libxext6/copyright
squashfs-root/usr/share/doc/libxfixes3
squashfs-root/usr/share/doc/libxfixes3/copyright
squashfs-root/usr/share/doc/libxi6
squashfs-root/usr/share/doc/libxi6/copyright
squashfs-root/usr/share/doc/libxinerama1
squashfs-root/usr/share/doc/libxinerama1/copyright
squashfs-root/usr/share/doc/libxkbcommon0
squashfs-root/usr/share/doc/libxkbcommon0/copyright
squashfs-root/usr/share/doc/libxrandr2
squashfs-root/usr/share/doc/libxrandr2/copyright
squashfs-root/usr/share/doc/libxrender1
squashfs-root/usr/share/doc/libxrender1/copyright
squashfs-root/usr/share/doc/libxtst6
squashfs-root/usr/share/doc/libxtst6/copyright
squashfs-root/usr/share/doc/libxxf86vm1
squashfs-root/usr/share/doc/libxxf86vm1/copyright
squashfs-root/usr/share/icons
squashfs-root/usr/share/icons/hicolor
squashfs-root/usr/share/icons/hicolor/128x128
squashfs-root/usr/share/icons/hicolor/128x128/apps
squashfs-root/usr/share/icons/hicolor/160x160
squashfs-root/usr/share/icons/hicolor/160x160/apps
squashfs-root/usr/share/icons/hicolor/160x160/apps/icon.png
squashfs-root/usr/share/icons/hicolor/16x16
squashfs-root/usr/share/icons/hicolor/16x16/apps
squashfs-root/usr/share/icons/hicolor/256x256
squashfs-root/usr/share/icons/hicolor/256x256/apps
squashfs-root/usr/share/icons/hicolor/32x32
squashfs-root/usr/share/icons/hicolor/32x32/apps
squashfs-root/usr/share/icons/hicolor/64x64
squashfs-root/usr/share/icons/hicolor/64x64/apps
squashfs-root/usr/share/icons/hicolor/scalable
squashfs-root/usr/share/icons/hicolor/scalable/apps
	linux-vdso.so.1 (0x00007ffe539bd000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f31c75cf000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f31c73b9000)
	libdbus-1.so.3 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libdbus-1.so.3 (0x00007f31c7167000)
	libxkbcommon.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libxkbcommon.so.0 (0x00007f31c6f27000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f31c6de6000)
	libXtst.so.6 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libXtst.so.6 (0x00007f31c6bdf000)
	libssl.so.1.1 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libssl.so.1.1 (0x00007f31c694b000)
	libcrypto.so.1.1 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libcrypto.so.1.1 (0x00007f31c646a000)
	libwx_gtk3u_html-3.0.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libwx_gtk3u_html-3.0.so.0 (0x00007f31c6187000)
	libwx_gtk3u_adv-3.0.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libwx_gtk3u_adv-3.0.so.0 (0x00007f31c5d8e000)
	libwx_gtk3u_core-3.0.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libwx_gtk3u_core-3.0.so.0 (0x00007f31c5510000)
	libwx_baseu-3.0.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libwx_baseu-3.0.so.0 (0x00007f31c5062000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f31c5045000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f31c503a000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f31c5019000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f31c4ed5000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f31c4ece000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f31c4d02000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f31c82be000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f31c4cfb000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f31c4cf3000)
	libsystemd.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libsystemd.so.0 (0x00007f31c4a6b000)
	libXext.so.6 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libXext.so.6 (0x00007f31c4857000)
	libgtk-3.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libgtk-3.so.0 (0x00007f31c3f21000)
	libgdk-3.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libgdk-3.so.0 (0x00007f31c3c1f000)
	libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007f31c3bbc000)
	libcairo.so.2 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libcairo.so.2 (0x00007f31c389a000)
	libgdk_pixbuf-2.0.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libgdk_pixbuf-2.0.so.0 (0x00007f31c3674000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f31c361a000)
	libglib-2.0.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libglib-2.0.so.0 (0x00007f31c32f9000)
	libnotify.so.4 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libnotify.so.4 (0x00007f31c30ee000)
	libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007f31c30dd000)
	libXxf86vm.so.1 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libXxf86vm.so.1 (0x00007f31c2ed6000)
	libSM.so.6 => /usr/lib/libSM.so.6 (0x00007f31c2ecc000)
	libpng16.so.16 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libpng16.so.16 (0x00007f31c2c98000)
	libjpeg.so.8 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libjpeg.so.8 (0x00007f31c2a2f000)
	libtiff.so.5 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libtiff.so.5 (0x00007f31c27b4000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f31c279a000)
	liblzma.so.5 => /home/lucio/opt/squashfs-root/usr/bin/../lib/liblzma.so.5 (0x00007f31c2573000)
	liblz4.so.1 => /home/lucio/opt/squashfs-root/usr/bin/../lib/liblz4.so.1 (0x00007f31c2356000)
	libgcrypt.so.20 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libgcrypt.so.20 (0x00007f31c2038000)
	libgmodule-2.0.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libgmodule-2.0.so.0 (0x00007f31c1e31000)
	libXi.so.6 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libXi.so.6 (0x00007f31c1c20000)
	libXfixes.so.3 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libXfixes.so.3 (0x00007f31c1a19000)
	libcairo-gobject.so.2 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libcairo-gobject.so.2 (0x00007f31c180f000)
	libatk-1.0.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libatk-1.0.so.0 (0x00007f31c15e6000)
	libatk-bridge-2.0.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libatk-bridge-2.0.so.0 (0x00007f31c13b1000)
	libepoxy.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libepoxy.so.0 (0x00007f31c1096000)
	libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007f31c107d000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f31c102e000)
	libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007f31c0e6e000)
	libXinerama.so.1 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libXinerama.so.1 (0x00007f31c0c6a000)
	libXrandr.so.2 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libXrandr.so.2 (0x00007f31c0a5c000)
	libXcursor.so.1 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libXcursor.so.1 (0x00007f31c0851000)
	libXcomposite.so.1 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libXcomposite.so.1 (0x00007f31c064d000)
	libXdamage.so.1 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libXdamage.so.1 (0x00007f31c0449000)
	libwayland-cursor.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libwayland-cursor.so.0 (0x00007f31c0240000)
	libwayland-egl.so.1 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libwayland-egl.so.1 (0x00007f31c003d000)
	libwayland-client.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libwayland-client.so.0 (0x00007f31bfe2b000)
	libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x00007f31bfe0b000)
	libthai.so.0 => /usr/lib/libthai.so.0 (0x00007f31bfe00000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f31bfd27000)
	libpixman-1.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libpixman-1.so.0 (0x00007f31bfa80000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f31bf9b5000)
	libxcb-shm.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libxcb-shm.so.0 (0x00007f31bf7af000)
	libxcb-render.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libxcb-render.so.0 (0x00007f31bf59f000)
	libXrender.so.1 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libXrender.so.1 (0x00007f31bf394000)
	libffi.so.8 => /usr/lib/libffi.so.8 (0x00007f31bf388000)
	libpcre.so.3 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libpcre.so.3 (0x00007f31bf115000)
	libICE.so.6 => /usr/lib/libICE.so.6 (0x00007f31bf0f6000)
	libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f31bf0ed000)
	libjbig.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libjbig.so.0 (0x00007f31beede000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f31beeb6000)
	libatspi.so.0 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libatspi.so.0 (0x00007f31bec81000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f31bec4f000)
	libmount.so.1 => /usr/lib/libmount.so.1 (0x00007f31bebef000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f31bebd5000)
	libffi.so.6 => /home/lucio/opt/squashfs-root/usr/bin/../lib/libffi.so.6 (0x00007f31be9cc000)
	libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x00007f31be9c2000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f31be99b000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f31be988000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007f31be97a000)
	libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f31be924000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007f31be901000)

**Comment by Vistaus** [comment] 2021-12-18 14:03
I have the same issue. I moved to Void Linux yesterday, and since there's no Espanso binary available, I tried the AppImage, but ran into this issue.

**Comment by federico-terzi** [comment] 2021-12-18 14:39
Thanks guys! It seems to be a common problem, happening to multiple app images:
* https://github.com/VSCodium/vscodium/issues/919
* https://github.com/FastTrackOrg/FastTrack/issues/25
* https://forum.manjaro.org/t/vscodium-appimage-wont-launch-symbol-lookup-error-libgio/84462/3
* https://bbs.archlinux.org/viewtopic.php?id=269838

I've opened another issue for now https://github.com/AppImage/AppImageKit/issues/1162
Also, this PR might be helpful to debug this further: https://github.com/VSCodium/vscodium/pull/944/files#

I'll keep you posted, thanks!

**Comment by federico-terzi** [comment] 2021-12-21 21:44
@Luciofulci @Vistaus When you have the chance, could you please retry with this AppImage? You can find it under the "Artifacts" section > Linux X11: https://github.com/federico-terzi/espanso/actions/runs/1608486594

Following these instructions: https://espanso.org/docs/next/install/linux/#installing-with-appimage

Let me know if that helps :)

**Comment by Luciofulci** [comment] 2021-12-23 00:04
Hi, man. Thanks for all the effort. I got this error in the third step.

/home/lucio/opt/Espanso-X11.AppImage: symbol lookup error: /usr/lib/libgobject-2.0.so.0: undefined symbol: g_atomic_rc_box_release_full


I double-checked if I had uninstalled the previous version and double-checked if I have my X11 session.

**Comment by federico-terzi** [comment] 2021-12-24 19:57
@Luciofulci Thanks! I'll investigate

**Comment by federico-terzi** [comment] 2021-12-25 14:11
@Luciofulci I was able to reproduce it on my machine, when you have the chance could you please try this build? :) https://github.com/federico-terzi/espanso/actions/runs/1621751285

**Comment by Luciofulci** [comment] 2021-12-31 03:11
Ufff, installs perfectly fine @federico-terzi I will use it a couple of days and report anything back. Thanks for everything!

**Comment by federico-terzi** [comment] 2022-01-01 11:22
Thanks! Closing this issue for now, feel free to reopen if necessary :)

**Comment by maisotro** [comment] 2022-03-22 13:49
i'm having the same problem on the release v2.1.4-beta

**Comment by federico-terzi** [comment] 2022-03-23 19:55
@maisotro Sorry to hear that! Perhaps something has changed in the AppImage repository. I'm reopening the issue until we're able to investigate further :)

**Comment by faermanj** [comment] 2022-03-28 15:19
I have a similar issue
`/home/faermanj/opt/Espanso.AppImage: symbol lookup error: /lib64/libgobject-2.0.so.0: undefined symbol: g_uri_ref
`

**Comment by federico-terzi** [comment] 2022-03-28 19:11
@faermanj I'm sorry you experienced this problem! Please try downloading the nightly release from here: https://github.com/federico-terzi/espanso/actions/runs/2048796020 (under Linux X11 Artifacts), the rest of the installation process is the same :)

Will release the fix in the upcoming days

**Comment by faermanj** [comment] 2022-03-29 07:09
hello @federico-terzi thanks for helping out! I tried removing / isntalling from nightly but still not successfully.
Here is what happened:
```
[faermanj@fedora espanso]$ espanso service register
service file already exists, this operation will overwrite it
creating service file in "/home/faermanj/.config/systemd/user/espanso.service"
enabling systemd service
service registered correctly!
[faermanj@fedora espanso]$ espanso start
unable to start service: timed out
```
Nothing too interesting in the log:
```
09:05:41 [service(29009)] [WARN] service file already exists, this operation will overwrite it
09:05:41 [service(29009)] [INFO] creating service file in "/home/faermanj/.config/systemd/user/espanso.service"
09:05:41 [service(29009)] [INFO] enabling systemd service
09:05:41 [service(29009)] [INFO] service registered correctly!
09:06:00 [service(29193)] [INFO] reading configs from: "/home/faermanj/.config/espanso"
09:06:00 [service(29193)] [INFO] reading packages from: "/home/faermanj/.config/espanso/match/packages"
09:06:00 [service(29193)] [INFO] using runtime dir: "/home/faermanj/.cache/espanso"
09:06:07 [service(29193)] [ERROR] unable to start service: timed out

```

**Comment by faermanj** [comment] 2022-03-29 17:37
@federico-terzi nevermind me, my mistake, i was using the wrong binary.
Reverted the system to X11 and all is good.

**Comment by kepford** [comment] 2022-03-30 03:54
I am also seeing this on Fedora 35 X11 with the app image install of v2.1.4-beta.

```
sudo ~/opt/Espanso.AppImage env-path register
[sudo] password for kepford:
/home/kepford/opt/Espanso.AppImage: symbol lookup error: /lib64/libgobject-2.0.so.0: undefined symbol: g_uri_ref
```

**Comment by federico-terzi** [comment] 2022-03-30 18:58
@kepford I'm sorry you experienced this problem! I'm releasing version 2.1.5-beta with a fix soon, should be available in ~2 hours

**Closed** 2022-07-02 13:13 UTC
Labels: bug, Linux, High priority
