### ISSUE TITLE
Espanso causes macOS's Spotlight to open when pressing CMD+C

### ISSUE THREAD

**Issue by yosamsimiti** [espanso/espanso#715] opened 2021-07-26 22:32 UTC
I'm on a mac, and when repeatedly need to paste things, after the third or fourth time does Spotlight suddenly get triggered, and the last thing that I wanted to paste, gets unpasted (that is, deleted).

**Comment by federico-terzi** [comment] 2021-07-29 17:57
Hey @yosamshiyam,

I'm sorry you experienced this problem! I think I might have a rough idea of what could be causing this, I'll investigate and get back to you if I discover something!

Cheers :)

**Comment by yosamshiyam** [comment] 2021-08-02 15:49
As a make shift solution, what I do, is with every repeated past, just before I paste, I press the arrow keys to go back a character or two, and then bring it back to where I was.  The error almost if not always does not occur.  But this is annoying as hell, especially if you have to do repeated pastes over and over again.  But I thought I should let you, this is my make-shift fix

**Comment by federico-terzi** [comment] 2021-08-04 16:42
@yosamshiyam thank you for letting me know, these could be useful while investigating :)

**Comment by federico-terzi** [comment] 2021-08-29 15:03
@r-martins @yosamshiyam Thank you guys, especially for the youtube video. That makes it particularly clear (if you can, please leave it online until the issue is marked as solved).

I still haven't found the cause but I'll make sure to let you know once I find something!

**Comment by r-martins** [comment] 2021-08-29 21:40
Thanks @federico-terzi. The video will be there. I don't plan to remove it at least hehe.
Let me know if I can help you in anyway to reproduce it. ;)

**Comment by federico-terzi** [comment] 2021-08-30 20:10
@r-martins Thank you! For now, I think our best bet is to check if the problem still occurs once the v2 alpha goes public :) I'll keep you posted

**Comment by yosamshiyam** [comment] 2021-09-09 19:28
It looks like selecting all (cmd-A) also triggers spotlight and deletes everything that's selected.  Just thought to add this as this is new, I feel

**Comment by r-martins** [comment] 2021-09-09 21:59
Yeh.. I've been disabling Espanso while developing or editing video/images. 
Let's wait for v2. 🤞

**Comment by smeech** [comment] 2024-02-13 14:39
Is this still a problem with current versions of macOS & Espanso?

**Closed by smeech** 2024-02-13 14:39 UTC
Labels: bug, MacOS

**Comment by r-martins** [comment] 2024-02-13 23:31
I'm using 2.1.8 now, and it's not happening anymore.

**Comment by smeech** [comment] 2024-02-13 23:35
Thank you for replying after all this time. We're now up to v2.2.1 with the increased number of people involved.
