### ISSUE TITLE
`.yaml` extension not loading

### ISSUE THREAD

**Issue by krystof-k** [espanso/espanso#1316] opened 2022-07-29 12:17 UTC
When creating config with `.yaml` instead of `.yml`, it doesn't load. 

I totally get that you chose to use `.yml` and that's perfectly fine, however it would be nice if `.yaml` also works, as it is [the official YAML extension](https://yaml.org/faq.html).

**Setup information**
- OS: macOS Monterey 12.5 (21G72)
- Version: espanso 2.1.6-beta

**Comment by kpym** [comment] 2022-11-12 09:43
+1 : same in Windows.

**Comment by smeech** [comment] 2024-02-16 14:48
Duplicate of #385.

**Closed by smeech** 2024-02-16 14:48 UTC
Labels: bug, enhancement
