### ISSUE TITLE
Unclosable window appears on wayland

### ISSUE THREAD

**Issue by pesader** [espanso/espanso#1722] opened 2023-10-09 14:22 UTC
**Describe the bug**
When using espanso for wayland, an unclosable "Espanso Sync Tool" window appears. The window itself is small and resizable, so it doesn't seem to be intentional.

**To Reproduce**
1. Install espanso from the COPR [eclipseo/espanso](https://copr.fedorainfracloud.org/coprs/eclipseo/espanso/)
2. Enable and start the espanso service
3. Restart your computer and login
4. You should see the unclosable window

**Expected behavior**

**Screenshots**

| Mouse hovering over window | Window title in GNOME's dash |
|-|-|
|![Screenshot from 2023-10-09 10-53-29](https://github.com/espanso/espanso/assets/65264536/de4b7a06-5b07-4bdc-af13-510795fe6cfd)|![Screenshot from 2023-10-09 10-57-00](https://github.com/espanso/espanso/assets/65264536/d4f1e72a-0ed3-4230-bbcd-600331324275)|

**Logs**

```log
10:49:25] [INFO] reading configs from: "/var/home/pedro/.config/espanso"
10:49:25] [INFO] reading packages from: "/var/home/pedro/.config/espanso/match/packages"
10:49:25] [INFO] using runtime dir: "/var/home/pedro/.cache/espanso"
10:49:25] [INFO] system info: Fedora Linux v39 - kernel: 6.5.5-300.fc39.x86_64
10:49:25] [INFO] espanso version: 2.1.8
10:49:25] [INFO] spawning the worker process...
10:49:25] [INFO] binded to IPC unix socket: /var/home/pedro/.cache/espanso/espansodaemonv2.sock
10:49:25] [INFO] watching for changes in path: "/var/home/pedro/.config/espanso"
10:49:26] [INFO] reading configs from: "/var/home/pedro/.config/espanso"
10:49:26] [INFO] reading packages from: "/var/home/pedro/.config/espanso/match/packages"
10:49:26] [INFO] using runtime dir: "/var/home/pedro/.cache/espanso"
10:49:26] [INFO] system info: Fedora Linux v39 - kernel: 6.5.5-300.fc39.x86_64
10:49:26] [INFO] binded to IPC unix socket: /var/home/pedro/.cache/espanso/espansoworkerv2.sock
10:49:26] [INFO] using WaylandAppInfoProvider
10:49:26] [INFO] detection module will use this keyboard layout: [R=evdev, M=pc105, L=us, V=, O=]
10:49:26] [INFO] using EVDEVSource
10:49:26] [INFO] monitoring the status of the daemon process
10:49:26] [INFO] Querying modifier status...
10:49:31] [INFO] inject module will use this keyboard layout: [R=evdev, M=pc105, L=us, V=, O=]
10:49:31] [INFO] using EVDEVInjector
10:49:31] [INFO] using WaylandFallbackClipboard
11:03:10] [INFO] reading configs from: "/var/home/pedro/.config/espanso"
11:03:10] [INFO] reading packages from: "/var/home/pedro/.config/espanso/match/packages"
11:03:10] [INFO] using runtime dir: "/var/home/pedro/.cache/espanso"
11:03:10] [INFO] system info: Fedora Linux v39 - kernel: 6.5.5-300.fc39.x86_64
11:03:10] [ERROR] worker is already running!
```

**Setup information**
- OS: Fedora Silverblue 39
- Version: espanso 2.1.8

**Comment by raygan** [comment] 2023-11-27 15:51
I also see this on Fedora 39 when using Wayland Gnome

**Comment by federico-terzi** [comment] 2023-12-05 20:56
Interesting! Thanks for sharing

In theory, that window should close after the first initialization (it's used to gather the current keyboard layout, which IIRC requires a window on wayland)

**Comment by tprotopopescu** [comment] 2023-12-15 00:55
I complied from source and I'm seeing this on opensuse 15.5, KDE with Wayland.

**Comment by bmp** [comment] 2023-12-19 20:12
@pesader May I ask how you installed this on Silverblue?  `setcap` isn't permitted right? I get `Failed to set capabilities on file /usr/bin/espanso-wayland' (Read-only file system)` when I try the command in the wiki.

@raygan Are you using the COPR on Silverblue or on Fedora 39? In case it is Silverblue, have you followed any other steps apart from adding the COPR to repos and then layering `espanso-wayland`?

**Comment by raygan** [comment] 2023-12-19 20:48
> @raygan Are you using the COPR on Silverblue or on Fedora 39? In case it is Silverblue, have you followed any other steps apart from adding the COPR to repos and then layering `espanso-wayland`?

@bmp I was using Fedora 39, not Silverblue. I followed the steps here: https://discussion.fedoraproject.org/t/espanso-copr-available-for-testing/88921#!

I ended up with the unclosable window issue. Later for unrelated reasons I did a full Fedora reinstall, and instead compiled from source, and didn’t have the issue; it’s been working fine since.

**Comment by pesader** [comment] 2023-12-19 23:56
> @pesader May I ask how you installed this on Silverblue?  `setcap` isn't permitted right? I get `Failed to set capabilities on file /usr/bin/espanso-wayland' (Read-only file system)` when I try the command in the wiki.

I used the COPR package for `espanso-wayland`, which sets the capabilities needed for Espanso to function.

**Comment by pesader** [comment] 2023-12-19 23:58
@raygun perhaps an older release of Espanso is being packaged, hence you didn't have the same issue when you compiled the code yourself. I'd have to check, though.

Edit: the version being packaged in COPR is 2.1.8-1, while the latest version of Espanso is 2.2.1.

**Comment by bmp** [comment] 2023-12-20 04:36
> > @pesader May I ask how you installed this on Silverblue?  `setcap` isn't permitted right? I get `Failed to set capabilities on file /usr/bin/espanso-wayland' (Read-only file system)` when I try the command in the wiki.
> 
> I used the COPR package for `espanso-wayland`, which sets the capabilities needed for Espanso to function.

@pesader Is this the [COPR](https://copr.fedorainfracloud.org/coprs/eclipseo/espanso/) you reference? If so, the Fedora [forum](https://discussion.fedoraproject.org/t/espanso-copr-available-for-testing/88921#) suggests adding setcap manually for `espanso-wayland`.

**Comment by bmp** [comment] 2023-12-20 04:58
@pesader Also, I get the same uncloseable window that I have reported [here](https://discussion.fedoraproject.org/t/espanso-copr-available-for-testing/88921/7) in case I start it as `espanso-wayland start --unmanaged`. I have posted there to see how to help with checking the package on COPR, but haven't heard back from the author.

**Comment by pesader** [comment] 2023-12-20 18:42
@bmp The espanso COPR package sets the needed POSIX capabilities all by itself. As you can see [here](https://download.copr.fedorainfracloud.org/results/eclipseo/espanso/fedora-39-x86_64/06562310-espanso/espanso.spec), this is done by the following line:

```bash
%caps(cap_dac_override=pe) %{_bindir}/espanso-wayland
```

`%caps` is an [undocumented](https://github.com/redhat-developer/rpm-packaging-guide/issues/58) RPM macro which sets POSIX capabilities. Anyway, because this is done by the rpm package itself, there's no need to set it up manually.

**Comment by bmp** [comment] 2023-12-22 05:31
@pesader Removed my overlayed package and the one I had installed through distrobox, and checked cap for espanso-wayland,

```
❯ getcap $(which espanso-wayland)
/usr/bin/espanso-wayland cap_dac_override=ep
```

And it is set, now I only have the issue of this window that won't go away!

**Comment by codechipped** [comment] 2024-01-13 06:41
I'm experiencing the same problem, likely for about a week or two now. It's difficult to pinpoint the exact start. I made two changes around that time: adding a second Activity and migrating to KeePassXC as my Secret Service. While I doubt they're directly related, the timing is coincidental.

![image](https://github.com/espanso/espanso/assets/29626515/5d1882ca-facf-4473-bbe2-14134d8156c7)

I initially had Espanso installed through the AUR, but when others reported success compiling it manually to fix their problems, I decided to give it a shot. Unfortunately, it didn't work for me.

![image](https://github.com/espanso/espanso/assets/29626515/39a77d9d-3ce9-46c3-a299-23be098fa887)

**Comment by bmp** [comment] 2024-01-17 12:01
@codechipped That is interesting, I use KeepassXC (on flatpak though) too, have you tried to see if this persists without KeepassXC?

**Comment by pesader** [comment] 2024-01-17 12:10
@bmp I have the issue without KeepassXC at all, I don't think this is related.

**Comment by theweekendgeek** [comment] 2024-01-17 23:09
Can confirm the bug on Fedora 39 & Gnome 45.2 & Wayland after a new intsall of espanso according to the docs.

**Comment by jfml** [comment] 2024-02-08 08:10
I have this issue with espenso 2.2.1 installed from source on Fedora 39 KDE spin as well, looks like the screenshot @codechipped posted (without „On wUti“), feel free to contact me if I can test anything ^ _ ^

**Comment by YT37** [comment] 2024-02-24 17:15
For those on KDE, there is an easy fix for now where the icon can be hidden from the taskbar using a window rule as shown in the picture.

![Screenshot_20240224_224108](https://github.com/espanso/espanso/assets/46230146/6af3cded-42db-449a-a7f9-e4e9f23d6dd9)

**Comment by onjour** [comment] 2024-02-25 15:51
Thanks @YT37! For those interested I exported [the rule](https://github.com/onjour/stash/blob/main/Hide-espanso-sync-window.kwinrule) so you can download it then import it in your Window Rules settings.

**Comment by acorazza** [comment] 2024-03-06 16:23
I just upgraded from KDE 5.27 (X11) to KDE 6  (Wayland) and have the exact same issue as shown in codechipped's screenshot. I installed Espanso from the AUR.

**Comment by GolDNenex** [comment] 2024-03-07 08:13
I was using a similar window rule (like the one shown before). 
The problem is worse since Plasma 6 because now, when shutting down or rebooting, Plasma wait for the window to close and something like 15/30sec after, a notification appears that ask the user to cancel or force.

**Comment by bmp** [comment] 2024-03-13 07:50
Are there any fixes for this apart from the workaround suggested by @YT37 and @onjour?

**Comment by morgan-dgk** [comment] 2024-03-13 13:18
@bmp not currently unfortunately. It appears that there are some keyboard events that are not being sent until the espanso sync tool window is closed. As the client is no longer listening for events sent by the wayland server, this cause an unresponsive client. 

update: I think I have located the cause of this issue. The PR request below should fix this.

**Comment by AucaCoyan** [comment] 2024-03-14 15:49
Hello! #1901 got merged, can we re-test if this keeps happening in the latest version? ❤️ 
this will probably close this as solved 🚀

**Comment by YT37** [comment] 2024-03-14 19:25
Hi @AucaCoyan, yes I can confirm both issues (the unclosable window and inability to log out) have been fixed for me (using KDE 6 on Arch if that matters).

**Comment by AucaCoyan** [comment] 2024-03-14 19:30
Thank you!

**Closed by AucaCoyan** 2024-03-14 19:30 UTC
Labels: bug

**Comment by Djeremaille** [comment] 2024-05-18 07:05
Hi, 
I'm actually on kde-neon 6.0 and espanso 2.2.1 from the ppa deb package and the bug is present.
Do you plan to update the package soon or I have to build it myself?

**Comment by smeech** [comment] 2024-05-18 08:13
> Hi, I'm actually on kde-neon 6.0 and espanso 2.2.1 from the ppa deb package and the bug is present. Do you plan to update the package soon or I have to build it myself?

I don't think a new release is imminent. Compiling is generally straightforward if you're in a hurry to have the latest changes.

**Comment by Djeremaille** [comment] 2024-05-19 10:04
> > Hi, I'm actually on kde-neon 6.0 and espanso 2.2.1 from the ppa deb package and the bug is present. Do you plan to update the package soon or I have to build it myself?
> 
> I don't think a new release is imminent. Compiling is generally straightforward if you're in a hurry to have the latest changes.

Done. It seems to work correctly.
Thanks!

**Comment by moshpirit** [comment] 2025-03-16 12:08
This is happening to me on wayland sessions even after completely removing the app via `sudo paman -Rns espanso-wayland` (I even tried using the git version and the X11 version when using wayland, yet this keeps appearing). What is causing this and how can I completely get rid of this?
