### ISSUE TITLE
I created json schema files for espanso config

### ISSUE THREAD

**Issue by chrisgrieser** [espanso/espanso#1721] opened 2023-10-08 10:36 UTC
type safety & validation, in case you have more complex espanso configurations. Not sure where to share this, but maybe someone else might also find them useful.

Maybe they can be added to the docs and/or builtin automatically via schema-store?

https://gist.github.com/chrisgrieser/aff1d162fa247792ad6b34dec000082d#file-how-to-use-md

**Comment by AucaCoyan** [comment] 2024-11-13 12:40
duplicate of #1917

**Closed by AucaCoyan** 2024-11-13 12:40 UTC
