### ISSUE TITLE
Search Bar won't open in macOS Ventura RC 2

### ISSUE THREAD

**Issue by txfengj** [espanso/espanso#1413] opened 2022-10-21 14:46 UTC
**Describe the bug**
Search Bar won't open in macOS Ventura RC 2, and if you try to open it, the whole espanso stops working and needs to be restarted.

**To Reproduce**
1. click 'open search bar'

**Expected behavior**
the search bar shows up

**Screenshots**
not applicable for this bug

**Logs**
22:39:20 [daemon(9867)] [INFO] reading configs from: "/Users/john/Library/Application Support/espanso"
22:39:20 [daemon(9867)] [INFO] reading packages from: "/Users/john/Library/Application Support/espanso/match/packages"
22:39:20 [daemon(9867)] [INFO] using runtime dir: "/Users/john/Library/Caches/espanso"
22:39:20 [daemon(9867)] [INFO] system info: Darwin v13.0 - kernel: 22.1.0
22:39:20 [daemon(9867)] [INFO] watching for changes in path: "/Users/john/Library/Application Support/espanso"
22:39:20 [daemon(9867)] [INFO] espanso version: 2.1.7-beta
22:39:20 [daemon(9867)] [INFO] spawning the worker process...
22:39:20 [daemon(9867)] [INFO] binded to IPC unix socket: /Users/john/Library/Caches/espanso/espansodaemonv2.sock
22:39:20 [worker(9868)] [INFO] reading configs from: "/Users/john/Library/Application Support/espanso"
22:39:20 [worker(9868)] [INFO] reading packages from: "/Users/john/Library/Application Support/espanso/match/packages"
22:39:20 [worker(9868)] [INFO] using runtime dir: "/Users/john/Library/Caches/espanso"
22:39:20 [worker(9868)] [INFO] system info: Darwin v13.0 - kernel: 22.1.0
22:39:20 [worker(9868)] [INFO] using CocoaAppInfoProvider
22:39:20 [worker(9868)] [INFO] binded to IPC unix socket: /Users/john/Library/Caches/espanso/espansoworkerv2.sock
22:39:20 [worker(9868)] [INFO] using CocoaSource
22:39:20 [worker(9868)] [INFO] monitoring the status of the daemon process
22:39:20 [worker(9868)] [INFO] using MacInjector
22:39:20 [worker(9868)] [INFO] monitoring the status of secure input
22:39:20 [worker(9868)] [INFO] using CocoaClipboard

**Setup information**
- OS: macOS Ventura RC 2
- Version: 2.1.7

**Comment by metrobee** [comment] 2022-10-27 17:48
same here!

**Comment by dacianf** [comment] 2022-10-27 21:20
Same on my side
MacOS 13.0 (22A380)

**Comment by DiastroGit** [comment] 2022-10-28 10:06
+1, not just on RC, also not working in the actual release of Ventura.

**Comment by bartvandeweerdt** [comment] 2022-10-28 12:45
+1, seems to crash after trying to open the search bar

**Comment by federico-terzi** [comment] 2022-10-28 14:49
Hey guys,
I'm sorry you are experiencing this issue! Could you please check if after trying to open the search bar, a crash dump is produced? It would be amazingly helpful if you could post it here :)
https://support.apple.com/guide/console/reports-cnsl664be99a/mac

Cheers :)

**Comment by txfengj** [comment] 2022-10-28 15:01
> Hey guys, I'm sorry you are experiencing this issue! Could you please check if after trying to open the search bar, a crash dump is produced? It would be amazingly helpful if you could post it here :) https://support.apple.com/guide/console/reports-cnsl664be99a/mac
> 
> Cheers :)

No, there's no related crash reports.

**Comment by inDeXing1** [comment] 2022-10-28 18:31
I have the same problem.
Not sure if it‘s useful, but my logs also showed this:

17:32:37 [worker(46498)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
17:51:36 [worker(46498)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
17:51:37 [worker(46498)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
19:54:37 [worker(46498)] [INFO] secure input has been disabled

**Comment by RicoLaaa** [comment] 2022-10-28 20:14
as said by @txfengj there is no reports.
If I quit the process that appears while calling the search bar, without quitting espanso, everything seems to work again.
But no logs other than:

`22:11:02 [worker(9361)] [ERROR] modulo exited with non-zero status code: None
22:11:02 [worker(9361)] [ERROR] SearchUI reported an error: modulo returned an empty output`

but that's just saying that I killed the process and nothing about what happened just before..

**Comment by crisnoh** [comment] 2022-10-30 06:02
+1 on the search bar causing crashes

**Comment by federico-terzi** [comment] 2022-10-30 22:01
Hey guys,
thank you for the updates, I managed to reproduce the error and opened a PR with a fix. Hopefully, we'll have a new version released in the upcoming days :)

**Comment by federico-terzi** [comment] 2022-11-01 12:49
The latest version (2.1.8) fixes this issue :)

**Closed by federico-terzi** 2022-11-01 12:49 UTC
Labels: bug

**Comment by DiastroGit** [comment] 2022-11-02 08:04
Fantastic, thanks so much!

**Comment by KyleSnodgrass** [comment] 2022-11-16 02:03
Can't tell you how much this helps me every day. I love your work @federico-terzi ! Thanks for everything!

**Comment by drfurtado** [comment] 2022-12-15 21:33
I am using the latest version of Ventura OS and espanso but still unable to make it work.
https://www.screencast.com/t/y5yB4WhTX3

**Comment by piotr-szewczuk** [comment] 2022-12-16 07:47
Espanso 2.1.8 + Ventura 13.1 (22C65) works fine on my machine :)

**Comment by lightDer** [comment] 2023-01-12 01:06
Hi @drfurtado In the System settings -> Privacy & security -> Accessibility, try to remove(-) espanso and add(+) again.
It works on my mac (13.1).
![CleanShot 2023-01-12 at 09 05 55](https://user-images.githubusercontent.com/3839494/211951516-74036804-5a30-4b7c-8350-879269b64e25.png)

**Comment by drfurtado** [comment] 2023-01-13 15:46
Thanks for replying. I can confirm that by removing and adding it again does fix the issue.
