### ISSUE TITLE
Unmet dependency in Linux Mint 21 (libssl1.1 (>= 1.1.0))

### ISSUE THREAD

**Issue by ReaderGuy42** [espanso/espanso#1330] opened 2022-08-10 13:30 UTC
**Describe the bug**
When trying to install in an upgraded system (Linux Mint 20.3 to 21), I get an error of an unmet dependency.
**To Reproduce**
```
sudo apt install ./espanso-debian-x11-amd64.deb  
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'espanso' instead of './espanso-debian-x11-amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 espanso : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Setup information**
- OS: Linux Mint 21

Thanks!

**Comment by federico-terzi** [comment] 2022-08-13 09:00
Hey @ReaderGuy42,

This is a duplicate of https://github.com/espanso/espanso/issues/1056, I'm closing this one in favor of the other one. Feel free to continue the discussion there :)

Cheers :)

**Closed by federico-terzi** 2022-08-13 09:00 UTC
Labels: bug
