### ISSUE TITLE
X11AppInfoProvider on Wayland

### ISSUE THREAD

**Issue by starise** [espanso/espanso#1026] opened 2022-03-21 00:11 UTC
**Describe the bug**
Installed espanso-git via AUR but it does not work. Looking at `espanso log` it says `using X11AppInfoProvider` but it looks weird to me because I'm on Wayland.

**Logs**
```sh
[svitato@archelite ~]$ echo $XDG_SESSION_TYPE
wayland
[svitato@archelite ~]$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us
[svitato@archelite ~]$ cat ~/.config/espanso/config/default.yml 
backend: Auto
keyboard_layout:
  layout: "us"
[svitato@archelite ~]$ espanso log
01:01:34 [daemon(21474)] [INFO] reading configs from: "/home/svitato/.config/espanso"
01:01:34 [daemon(21474)] [INFO] reading packages from: "/home/svitato/.config/espanso/match/packages"
01:01:34 [daemon(21474)] [INFO] using runtime dir: "/home/svitato/.cache/espanso"
01:01:34 [daemon(21474)] [INFO] watching for changes in path: "/home/svitato/.config/espanso"
01:01:34 [daemon(21474)] [INFO] espanso version: 2.1.4-beta
01:01:34 [daemon(21474)] [INFO] spawning the worker process...
01:01:34 [daemon(21474)] [INFO] binded to IPC unix socket: /home/svitato/.cache/espanso/espansodaemonv2.sock
01:01:34 [worker(21482)] [INFO] reading configs from: "/home/svitato/.config/espanso"
01:01:34 [worker(21482)] [INFO] reading packages from: "/home/svitato/.config/espanso/match/packages"
01:01:34 [worker(21482)] [INFO] using runtime dir: "/home/svitato/.cache/espanso"
01:01:34 [worker(21482)] [INFO] using X11AppInfoProvider
01:01:34 [worker(21482)] [INFO] binded to IPC unix socket: /home/svitato/.cache/espanso/espansoworkerv2.sock
01:01:34 [worker(21482)] [INFO] using X11Source
01:01:34 [worker(21482)] [INFO] monitoring the status of the daemon process
01:01:34 [worker(21482)] [INFO] using X11Injector
01:01:35 [worker(21482)] [INFO] using X11Clipboard
````

**Setup information**
- OS: ArchLinux, Gnome 41.3, Wayland 
- Version: espanso 2.1.4-beta

**Comment by federico-terzi** [comment] 2022-03-23 19:51
Hey @starise,

Thanks for reporting this issue! I suspect you might have installed the X11 version by not providing the right flags to the install command (sorry, we still have a long way towards good documentation for wayland! :)

The problem is, I don't know the correct flag to pass, but I know it's there https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=espanso-git#n20

Perhaps, @Scrumplex can help? :) I'd love to know the exact command we should use to install (and compile) the wayland version of espanso

Cheers :)

**Comment by Scrumplex** [comment] 2022-03-23 22:23
Right now the AUR package relies on manually pulling the PKGBUILD, changing the flag in line 3 and subsequently building the package. I thought about maintaining two packages to make it easier for people to choose the right one

**Comment by starise** [comment] 2022-03-24 19:22
Thanks @federico-terzi the AUR package was the issue, I didn't think it was due to compilation process. I manually built the package locally changing `_wayland=true` into the PKGBUILD and it works nicely now. @Scrumplex this manual process though is pretty annoying, if it can be improved in the future it could be nice. 🙂

**Comment by Scrumplex** [comment] 2022-03-25 17:50
I am happy to report that I have split off `espanso-git`'s Wayland packaging into `espanso-wayland-git`. This should make it way more convenient to install it on Wayland (also more convenient for me :D)

While I am here, @federico-terzi, do you think the AUR package should track the `dev` branch, or should it always track `master`? Right now it's building off of `dev`, but I am currently thinking about switching that over to `master` instead. What do you think?

**Comment by Scrumplex** [comment] 2022-03-25 17:52
Also: do you think it's time for [espanso](https://aur.archlinux.org/packages/espanso) and [espanso-bin](https://aur.archlinux.org/packages/espanso-bin) to upgrade to 2.x?

**Comment by federico-terzi** [comment] 2022-03-25 20:17
> I am happy to report that I have split off espanso-git's Wayland packaging into espanso-wayland-git. This should make it way more convenient to install it on Wayland (also more convenient for me :D)

@Scrumplex Awesome! Thank you so much :) 

> While I am here, @federico-terzi, do you think the AUR package should track the dev branch, or should it always track master? Right now it's building off of dev, but I am currently thinking about switching that over to master instead. What do you think?

Yes, I agree, let's switch it to the `master` branch, as it's more stable :)

> Also: do you think it's time for [espanso](https://aur.archlinux.org/packages/espanso) and [espanso-bin](https://aur.archlinux.org/packages/espanso-bin) to upgrade to 2.x?

That would be great! The new release 2.1.4-beta is the new stable one, so we can go ahead with the switch :)
Before proceeding, I'd have a couple of questions:
* The new v2 doesn't have a binary release on Linux yet (and given the various incompatibilities with dependencies, I'm not sure whether it even makes sense to add). Do you think we should add it back? (I guess we should if we want to enable `espanso-bin` for the v2 right?)
* Given that we now have `espanso-wayland-git`, would it be possible to also create `espanso-wayland` and `espanso-wayland-bin` as well? 
* If we switch `espanso-git` to the `master` branch, would it make it equivalent to the `espanso` package?

Sorry for the many questions, I'm super curious about the your opinion :D

**Comment by Scrumplex** [comment] 2022-03-25 22:23
> * If we switch `espanso-git` to the `master` branch, would it make it equivalent to the `espanso` package?

Hmm. I wasn't aware of the release workflow you have on master. It would make `espanso` and `espanso-git` equivalent, so I will just keep it on `dev` then.


> * Given that we now have `espanso-wayland-git`, would it be possible to also create `espanso-wayland` and `espanso-wayland-bin` as well?

Yes!

> The new v2 doesn't have a binary release on Linux yet (and given the various incompatibilities with dependencies, I'm not sure whether it even makes sense to add). Do you think we should add it back? (I guess we should if we want to enable espanso-bin for the v2 right?)

I personally never use -bin packages anyway, but I know that many people prefer them. I don't know how much work it would be to package it properly. Maybe it's time for an AppImage and/or Flatpak? :D

**Comment by Scrumplex** [comment] 2022-03-25 22:50
Now there are `espanso` `espanso-wayland` `espanso-git` `espanso-wayland-git` on the AUR. The `-bin` is outdated for now.

**Comment by federico-terzi** [comment] 2022-03-27 17:08
@Scrumplex Wonderful, thank you for the help as always! :D 

>  I don't know how much work it would be to package it properly. Maybe it's time for an AppImage and/or Flatpak? :D

We _do_ have the AppImage (X11 only for now, as the `setcap` step required on Wayland doesn't work with AppImages out of the box), but it's not very stable yet :)

**Comment by smeech** [comment] 2024-02-15 12:07
I think all the issues in this thread have been dealt with so I'll close it for now. Correct me if I'm wrong and I'll reopen it!

**Closed by smeech** 2024-02-15 12:07 UTC
Labels: bug
