### ISSUE TITLE
tmux interference, with the tmux prefix character in the trigger and output

### ISSUE THREAD

**Issue by AndydeCleyre** [espanso/espanso#300] opened 2020-05-30 19:16 UTC
Thanks for this project, I like it very much!

I'm using:
Arch Linux
Konsole 20.04.1
tmux 3.1_b
espanso 0.6.1

I was getting a lot of garbled output for big expansions, with each of `Clipboard`, `Inject`, and `Auto` backends, but found in one of these bug reports a mention of the `fast_inject` option (I can't find it in the docs), and found good results with the combination:

```yml
backend: Clipboard
fast_inject: false
```

The only issue I notice now is in a tmux session, where I have in my `tmux.conf`:

```
set -g prefix `                                                                                                                                                
bind ` send-prefix
```

and in my `default.yml`:

```yml
backend: Clipboard
fast_inject: false
matches:
  - trigger: :`
    replace: |
      ```
      $|$
      ```
```

Normally within a session, I need to hit the backtick twice to enter that character literally, otherwise it just begins a tmux action, without actually printing that.

I expected with the above configuration that, within a tmux session, I would have to activate that espanso trigger by typing:

```
:``
```
as the first backtick should be swallowed by tmux.

It seems that espanso picks up on that first hit of the backtick, even though it's not normally printed, and the expansion is printed, but one of the backticks of the expansion text itself is swallowed up along the way.

Maybe this is the result of a race between espanso and tmux, where espanso wins, but tmux still finishes. 

The result is that inside a tmux session, in an editor such as nano or micro, hitting the two characters:

```
:`
```

Will result in:

````
``
```
CURSOR
````

When instead I'd expect it to:

1. not trigger until I hit the second backtick, and 
2. put three backticks on that first line, and position the cursor between the backtick lines

**Comment by AndydeCleyre** [comment] 2020-05-30 20:33
I found in another issue (though not in the docs?), mention of `inject_delay` and `backspace_delay`, and gave them both a try, but they don't help; I don't think they change the timing on the trigger *detection*.

I might be looking for something like a `trigger_delay` or `detect_delay` . . . I don't know.

**Comment by federico-terzi** [comment] 2020-05-31 08:04
Hey @AndydeCleyre 

Thank you for the feedback! I think the behaviour you are describing is the expected one with espanso. You see, espanso doesn't track printed characters but keypresses, so even though you don't see the first ` being printed, espanso intercepts it anyway.

What about changing the espanso trigger to:
```
:``
```

In this case espanso should wait until the second backtick to trigger the expansion.

Also keep in mind that espanso is mainly targeted at GUIs rather than terminal editors. So while it kinda works with terminals, the experience might not be the best.

Cheers :)

**Comment by AndydeCleyre** [comment] 2020-05-31 08:12
Thanks. Using that trigger fixes number 1, but the output is the same (two backticks on first line, cursor after second backtick line).

I think there's always been a blank line (as is desired) between the backtick lines, I probably just didn't format it properly on GitHub.

Even if I remove the backtick from the trigger, that's the output (with e.g. `trigger: :backticks`)

**Comment by federico-terzi** [comment] 2020-05-31 11:59
All right, as soon as I get my hands on a Linux machine I'll try to reproduce the problem and get back to you :)

**Comment by AucaCoyan** [comment] 2023-12-12 15:27
Closing the issue because is referring to a very old build

**Closed by AucaCoyan** 2023-12-12 15:27 UTC
Labels: bug, Linux
