### ISSUE TITLE
Excessive RAM usage

### ISSUE THREAD

**Issue by astropanic** [espanso/espanso#1777] opened 2023-12-12 09:52 UTC
**Describe the bug**
The Espanso process is eating a ton of RAM

**To Reproduce**
Open Espanso and check the RAM usage

**Expected behavior**
I would not expect more than 200MB of RAM. For example the Onepassword application is taking 115MB RAM compared to a whopping 1,42GB RAM taken by Espanso, I have only 5 expansions set up.

**Screenshots**
<img width="1234" alt="Screenshot 2023-12-12 at 10 50 13" src="https://github.com/espanso/espanso/assets/39388/d1ea70b6-3a14-4b60-b143-e4974f2c9bf2">

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

**Setup information**
- OS: macOS Monterey
- Version: 2.1.8

**Comment by smeech** [comment] 2023-12-12 10:59
That's clearly not right - my Mint Xfce system runs three threads (although this can increase) totalling 98MB.
Are you able to list the individual threads and sizes?
Does `espanso restart`, or `espanso stop` followed by `espanso start`, reduce the RAM usage, and how quickly does it increase?

**Comment by smeech** [comment] 2023-12-12 11:06
Possible duplicate of [#1675](https://github.com/espanso/espanso/issues/1675).

**Comment by astropanic** [comment] 2023-12-12 13:50
I will not argue with you @smeech if this is right or not. Something is causing the memory consumption to rise to the mentioned levels where just this process is affected. I sent a screenshot as prove. Maybe some lib the program is using is misbehaving under OSX. Good for you on your Linux Mint it is working. It is not working for me though on OSX. Fiddling around with some cronjob setups like in the mentioned link to periodically restart the process makes no sense for me. I just wanted to point out there is an undesired behaviour when it comes to RAM usage under OSX.

**Comment by smeech** [comment] 2023-12-12 14:05
I'm sorry, my bad choice of words, perhaps - I simply meant that it's not working correctly, and, I agree, you shouldn't have to periodically restart Espanso to make it behave. I was seeking a little more detail to assist with resolving the problem in the future as, with the current pace of development, it may be a while before the bug can be addressed.

**Comment by federico-terzi** [comment] 2023-12-12 14:16
Thanks for reporting! Yes this is a duplicate of #1675 
No solution to it yet (seems to be [an obscure macOS bug](https://stackoverflow.com/questions/76893657/memory-leak-with-cocoas-addglobalmonitorforeventsmatchingmask?noredirect=1#comment135569206_76893657)). For now restarting is the only workaround I am aware of

**Closed by federico-terzi** 2023-12-12 14:16 UTC
Labels: bug, MacOS, High priority
