### ISSUE TITLE
Disable startup toast notification on Windows

### ISSUE THREAD

**Issue by mnissl** [espanso/espanso#1369] opened 2022-09-08 06:27 UTC
Is there a way to disable the toast notification on Windows when espanso starts up?

I don't want to disable toast notifications alltogether as I do find them useful when I alter my configuration and see that my changes were applied. But the startup notification is pointless to me.

**Comment by mnissl** [comment] 2022-12-01 07:17
As a quick fix, I disabled toast notifications for Windows Powershell as I have no other Powershell tool that uses toasts.

**Comment by smeech** [comment] 2024-02-16 23:03
Is this still an issue with the current release or, can we close it?

**Comment by ghost** [comment] 2024-02-18 13:42
> Is this still an issue with the current release or, can we close it?

It still happens, at least for linux. It would be great to be able to disable only that notification.

**Comment by smeech** [comment] 2024-02-18 13:54
Ah - I mistakenly thought "toast" notifications was a Windows term. 
I'm not unhappy with mine (Mint Xfce), I just choose how long they appear for, but there have been other requests to disable the _startup_ one, specifically: #1002 & #1726, and related #1116 & #1115.

**Comment by AucaCoyan** [comment] 2024-11-13 14:22
dupe of #1116

**Closed by AucaCoyan** 2024-11-13 14:22 UTC
Labels: enhancement
