### ISSUE TITLE
espanso wayland fails to install on Ubuntu 22.04 with `libssl1.1` package unavailable error

### ISSUE THREAD

**Issue by idcrook** [espanso/espanso#1056] opened 2022-04-04 03:13 UTC
**Describe the bug**

_espanso wayland_ fails to install on Ubuntu 22.04 beta. a dependency for `libssl1.1` is unable to be resolved.

**To Reproduce**

1. `sudo apt update && sudo apt upgrade`
1. `wget https://github.com/federico-terzi/espanso/releases/download/v2.1.5-beta/espanso-debian-wayland-amd64.deb`
1. `sudo apt install ./espanso-debian-wayland-amd64.deb`
  espanso-wayland : Depends: libssl1.1 (>= 1.1.0) but it is not installable
2. `sudo apt install libssl1.1`
 E: Package 'libssl1.1' has no installation candidate

**Expected behavior**

Expected to be able to install using instructions from <https://espanso.org/docs/install/linux/#deb-wayland>

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**

Output of `apt install` for `espanso`

```
sudo apt install ./espanso-debian-wayland-amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'espanso-wayland' instead of './espanso-debian-wayland-amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 espanso-wayland : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
and `libssl1.1`

```
sudo apt install libssl1.1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libssl1.1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.1' has no installation candidate
```

**Setup information**
- OS: What OS are you using?
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)

This was **espanso wayland v2.1.5-beta** from https://github.com/federico-terzi/espanso/releases/download/v2.1.5-beta/espanso-debian-wayland-amd64.deb

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Jammy Jellyfish (development branch)
Release:	22.04
Codename:	jammy
```

**Comment by federico-terzi** [comment] 2022-04-05 19:49
Hey @idcrook,

Thanks for reporting this issue! What do you see when you run the following command: `apt search libssl`?

Cheers :)

**Comment by idcrook** [comment] 2022-04-05 21:03
It is a strange situation. It looks like the package `libssl1.1` is being removed from jammy (22.04). see, e.g.

<https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libssl1.1&searchon=names>

it is not found for jammy.

```console
$ apt search libssl
Sorting... Done
Full Text Search... Done
cl-plus-ssl/jammy,jammy 20200609.gitff4634a-1build1 all
  Common Lisp interface to OpenSSL

dcmtk/jammy 3.6.6-5 amd64
  OFFIS DICOM toolkit command line utilities

dlang-openssl/jammy,jammy 2.0.0+1.1.0h-0.2 all
  D version of the C headers for openssl

libdcmtk-dev/jammy 3.6.6-5 amd64
  OFFIS DICOM toolkit development libraries and headers

libdcmtk16/jammy 3.6.6-5 amd64
  OFFIS DICOM toolkit runtime libraries

libssl-dev/jammy 3.0.2-0ubuntu1 amd64
  Secure Sockets Layer toolkit - development files

libssl-doc/jammy,jammy 3.0.2-0ubuntu1 all
  Secure Sockets Layer toolkit - development documentation

libssl-ocaml/jammy 0.5.10-1build2 amd64
  OCaml bindings for OpenSSL (runtime)

libssl-ocaml-dev/jammy 0.5.10-1build2 amd64
  OCaml bindings for OpenSSL

libssl-utils-clojure/jammy,jammy 3.3.0-1 all
  library for SSL certificate management on the JVM

libssl3/jammy,now 3.0.2-0ubuntu1 amd64 [installed,automatic]
  Secure Sockets Layer toolkit - shared libraries

perl-openssl-defaults/jammy,now 5build2 amd64 [installed,automatic]
  version compatibility baseline for Perl OpenSSL packages

r-cran-openssl/jammy 1.4.6+dfsg-1ubuntu1 amd64
  GNU R toolkit for encryption, signatures and certificates based on OpenSSL
```

**Comment by idcrook** [comment] 2022-04-05 21:28
BTW, `espanso` builds and runs successfully on same (Ubuntu 22.04 beta) host when following the compiling instructions from:
<https://espanso.org/docs/install/linux/#wayland-compile>

**Comment by idcrook** [comment] 2022-04-05 23:22
Something else I have just determined. Building the .deb on 22.04 beta host obviates the dependency.  

Building the .deb-s on fresh clone (using [build_deb.sh](https://github.com/federico-terzi/espanso/blob/master/.github/scripts/ubuntu/build_deb.sh) as guide), the dependency that caused error in released package is not preset.

And installing the resulting wayland .deb that was built installs correctly. 

`sudo apt install ./espanso-debian-wayland-amd64.deb`

### The locally built .deb:

```console
$ dpkg-deb --field target/debian/espanso-wayland_2.1.5-beta_amd64.deb Depends
libc6 (>= 2.34), systemd, libxkbcommon0, libxkbcommon0 (>= 0.5.0), libnotify-bin, libwxgtk3.0-gtk3-0v5 (>= 3.0.5.1+dfsg), libwxgtk3.0-gtk3-0v5, wl-clipboard, libssl3 (>= 3.0.0~~alpha1), libdbus-1-3 (>= 1.9.14), libstdc++6 (>= 11), libwxbase3.0-0v5 (>= 3.0.5.1+dfsg)

$ dpkg -L espanso-wayland
/usr
/usr/bin
/usr/bin/espanso
/usr/share
/usr/share/doc
/usr/share/doc/espanso-wayland
/usr/share/doc/espanso-wayland/README.md
/usr/share/doc/espanso-wayland/copyright
``` 

###  Released `v2.1.5-beta` wayland package

The dependencies on the (BROKEN for 22.04 beta) released `v2.1.5-beta` wayland package:

```shell
$ dpkg-deb --field espanso-debian-wayland-amd64.deb Depends
libxkbcommon0, libxkbcommon0 (>= 0.5.0), libdbus-1-3 (>= 1.9.14), libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg), libgcc1 (>= 1:4.2), libstdc++6 (>= 5), libwxgtk3.0-gtk3-0v5, systemd, wl-clipboard, libssl1.1 (>= 1.1.0), libwxbase3.0-0v5 (>= 3.0.4+dfsg), libc6 (>= 2.18), libnotify-bin
```

which reveals the problematic `libssl1.1 (>= 1.1.0)` dependency

**Comment by idcrook** [comment] 2022-04-06 13:42
> ### The locally built .deb:
> ```
> $ dpkg-deb --field target/debian/espanso-wayland_2.1.5-beta_amd64.deb Depends
> libc6 (>= 2.34), systemd, libxkbcommon0, libxkbcommon0 (>= 0.5.0), libnotify-bin, libwxgtk3.0-gtk3-0v5 (>= 3.0.5.1+dfsg), libwxgtk3.0-gtk3-0v5, wl-clipboard, libssl3 (>= 3.0.0~~alpha1), libdbus-1-3 (>= 1.9.14), libstdc++6 (>= 11), libwxbase3.0-0v5 (>= 3.0.5.1+dfsg)
> 
[...]
> which reveals the problematic `libssl1.1 (>= 1.1.0)` dependency


note: the 22.04 built version has `libssl3 (>= 3.0.0~~alpha1)`

**Comment by idcrook** [comment] 2022-04-07 16:31
In Ubuntu 22.04 jammy jellyfish `libssl1.1` has been superceded by `libssl3`. When Jammy is released,  the following files for espanso release will be affected for this to be handled appropriately on it.  there may be other changes required.

1. `.github/workflows/release.yml`
     - `linux-deb` job relies on `runs-on: ubuntu-latest` which is currently 20.04-based
     - this might be fine as the actual builds are performed within a docker image, which is built locally  
3. `.github/scripts/ubuntu/Dockerfile`
     - the FROM image used to build currently relies on `ubuntu:18.04` image 
     - same Dockerfile is also currently used to build a local image for `linux-x11` AppImage
     - for a working 22.04 build, the base image will need to be `ubuntu:22.04` to handle the updated dependencies
     - this may require an additional Dockerfile for 22.04 alongside the current scheme?
6. `.github/scripts/ubuntu/build_deb.sh`
     - a parallel naming scheme for the `libssl3` (jammy) release artifacts to distinguish from the 18.04/22.04 artifacts.

I've only considered the `linux-deb` job, there may be similar updates required for the `linux-x11` job for Ubuntu 22.04 compatibility. In my testing, ubuntu 22.04 support only applies to build/release steps. The existing espanso source code seems to work as expected on 22.04 (when built on/for 22.04 target).

**Comment by federico-terzi** [comment] 2022-04-09 18:56
Hey @idcrook,

Thank you for the detailed investigation! That's very helpful. I currently don't have much time to dig into it, but I'll definitely investigate
The biggest problem I see is that we can't build on Ubuntu 22, as the rule of thumb is always to build on the oldest version you want to support. If we built on Ubuntu 22, then it's very likely that previous versions would stop working

I would really prefer finding a way to support both without forking the build process... 
Cheers :)

**Comment by niksingh710** [comment] 2022-04-23 09:58
http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb

installing this manually and then installing espanso deb works fine.

**Comment by idcrook** [comment] 2022-04-25 14:08
> I would really prefer finding a way to support both without forking the build process... Cheers :)

I see your point. There could be a way to update the dependency to accept libssl1.1 or libssl3? I don't know enough about the capabilities there.   The rust crate for building the deb's is rather opaque to me, but there appears to be ways to specify explicit dependencies.

The release build process has multiple incompatible targets (X, wayland, appimage, e.g.). Is it possible that this (libssl1.1 vs. libssl3) could be viewed as another target?

**Comment by idcrook** [comment] 2022-04-25 14:15
changed title as Ubuntu 22.04 has been released

**Comment by niksingh710** [comment] 2022-04-25 15:54
> changed title as Ubuntu 22.04 has been released

It is not related to Wayland only xorg is affected too.

**Comment by cplerch** [comment] 2022-05-08 07:13
Found a simple workaround:

- First install libssl1.1 from here: http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1n-0+deb11u1_amd64.deb
- Then install espanso-wayland as described here: https://espanso.org/docs/install/linux/#deb-wayland

**Comment by federico-terzi** [comment] 2022-07-04 19:52
Hey guys :)
I've just merged a mitigation for this problem (removing the libssl dependency on Linux), when you have the chance could you please try with the nightly build available here? https://github.com/espanso/espanso/actions/runs/2612138406

It should appear in about an hour in the Artifacts section, under (Ubuntu-Debian Artifacts). If you could try it out in your system to verify it works it would be a great help!

Thanks

**Comment by fstamour** [comment] 2022-07-08 15:21
I'm getting the same error with the nightly build you linked

```
sudo apt install ./espanso-debian-x11-amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'espanso' instead of './espanso-debian-x11-amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 espanso : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I looked at the content of both wayland and x11 packages, and they both still list `libssl1.1` in their dependencies.

**Comment by vfournier11** [comment] 2022-07-15 14:31
I've tried editing the `DEBIAN/control` file inside the `.deb` but after the installation espanso doesn't as it's seem it's still requiring the shared library.
```
$ espanso 
espanso: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by brincowale** [comment] 2022-07-31 08:38
Still same issue with the builds from https://github.com/espanso/espanso/actions/runs/2612138406

**Comment by dodalovic** [comment] 2022-08-05 19:36
Hey, @federico-terzi did you have a chance to additionally look at this one?

**Comment by McThump** [comment] 2022-08-13 06:43
Hi @federico-terzi, any chance of a fix for this soon? I upgraded my desktop to Ubuntu 22.04 and can no longer use Espanso due to this issue.

**Comment by federico-terzi** [comment] 2022-08-13 09:04
Hey guys, sorry for the late reply :) I've been away for a while

I just pushed a fix for the deb package, when you have the chance could you please try the nightly release from here: https://github.com/espanso/espanso/actions/runs/2851415356

It should appear in about an hour in the Artifacts section, under (Ubuntu-Debian Artifacts). If you could try it out in your system to verify it works it would be a great help!

**Comment by dodalovic** [comment] 2022-08-13 17:56
seems to work

**Comment by M1chael** [comment] 2022-08-13 19:03
Confirm working on Linux Mint 21

**Comment by McThump** [comment] 2022-08-13 19:58
Works on Ubuntu 20.04.4 LTS. Thank you!

**Comment by ReaderGuy42** [comment] 2022-08-13 22:57
Perfect, thank you!

**Comment by federico-terzi** [comment] 2022-08-14 08:55
Nice 🚀 Thank you
I'll make sure to release these changes as an official release soon

**Comment by idcrook** [comment] 2022-08-14 13:45
>There could be a way to update the dependency to accept libssl1.1 or libssl3? I don't know enough about the capabilities there. The rust crate for building the deb's is rather opaque to me, but there appears to be ways to specify explicit dependencies.

@federico-terzi thank you for finding the solution for the `cargo deb` build! am including the salient command flags and arguments from your commit here as cookie crumbs for any others who encounter similar circumstances.

```sh
 -- --no-default-features --features "modulo vendored-tls"
```

**Comment by iverik-no** [comment] 2022-08-20 08:08
Having this issue on (K)ubuntu 22.04.


```Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'espanso' instead of './espanso-debian-x11-amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 espanso : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
10:04:07 -------------> ~ 
```

As far as I can tell, libssl1.* is deprecated.

Tried using the .deb linked in [this post (Artifacts)](https://github.com/espanso/espanso/issues/1056#issuecomment-1214054864), but to no avail.

**Comment by xazw** [comment] 2022-08-28 06:23
I can confirm that this problem is still existent on a fresh Pop!_OS (22.04) installation. The same error appears, i.e:

```
The following packages have unmet dependencies:
 espanso-wayland : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

```

The following is a workaround, until support for libssl3 is integrated. I've tested it, it works - in essence, you have to manually download/install Espanso 2.1.6, then libssl1.1:

```
wget https://github.com/federico-terzi/espanso/releases/download/v2.1.6-beta/espanso-debian-x11-amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
sudo dpkg -i ./libssl1.1_1.1.0g-2ubuntu4_amd64.deb
sudo apt install ./espanso-debian-x11-amd64.deb
rm -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb
```

Then proceed with:

```
espanso service register
espanso start
```

**Comment by Luctins** [comment] 2022-09-07 17:37
Under fedora you can still manually install this dependency under the package `openssl1.1-1:1.1.1n-1.fc36.x86_64`

**Comment by fstamour** [comment] 2022-10-18 15:21
> Works on Ubuntu 20.04.4 LTS. Thank you!

I can confirm that it works :) , same distribution and version, using X11

Note for future me:
1. `sudo apt install --fix-broken ./espanso-debian-x11-amd64.deb`
2. `espanso service register`
3. `espanso service start`

**Closed** 2022-11-01 09:01 UTC
Labels: bug, Linux
