### ISSUE TITLE
Investigate whether 1Password SecureInput interference can be mitigated

### ISSUE THREAD

**Issue by navxio** [espanso/espanso#612] opened 2021-03-07 13:36 UTC
I'm using it on macOS 11.2.2

espanso version 0.7.3

**Comment by federico-terzi** [comment] 2021-03-07 18:27
Hey @navxio,

I'm sorry you experienced this problem! Could you please post the output of `espanso log` here?

Cheers :)

**Comment by navxio** [comment] 2021-03-07 18:39
```
17:09:46 [ INFO] espanso version 0.7.3
17:09:46 [ INFO] using config path: /Users/nav/Library/Preferences/espanso
17:09:46 [ INFO] using package path: /Users/nav/Library/Application Support/espanso/packages
17:09:46 [ INFO] spawning worker process...
17:09:46 [ INFO] Binded to IPC unix socket: /Users/nav/Library/Application Support/espanso/espanso.sock
17:09:46 [ INFO] initializing worker process...
17:09:46 [ INFO] Status icon already initialized, skipping.
17:09:46 [ INFO] Status icon (disabled) already initialized, skipping.
17:09:46 [ INFO] watching for changes in path: /Users/nav/Library/Preferences/espanso
17:09:46 [ INFO] Initializing EspansoNotifyHelper in /Users/nav/Library/Application Support/espanso
17:09:46 [ INFO] EspansoNotifyHelper already initialized, skipping.
17:09:46 [ INFO] Binded to IPC unix socket: /Users/nav/Library/Application Support/espanso/worker.sock
17:09:48 [ INFO] Using modulo at "/usr/local/bin/modulo"
17:09:48 [ INFO] Created Modulo APP stub at: "/Users/nav/Library/Application Support/espanso/Modulo.app/Contents/MacOS/modulo"
17:09:48 [ INFO] worker is running!
17:19:11 [ INFO] SecureInput has been acquired by Firefox, preventing espanso from working correctly. Full path: /Applications/Firefox.app/Contents/MacOS/firefox
17:19:16 [ INFO] SecureInput has been disabled.
17:25:27 [ INFO] SecureInput has been acquired by Firefox, preventing espanso from working correctly. Full path: /Applications/Firefox.app/Contents/MacOS/firefox
17:25:37 [ INFO] SecureInput has been disabled.
17:25:47 [ INFO] SecureInput has been acquired by Firefox, preventing espanso from working correctly. Full path: /Applications/Firefox.app/Contents/MacOS/firefox
17:26:02 [ INFO] SecureInput has been disabled.
05:34:56 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
05:35:01 [ INFO] SecureInput has been disabled.
07:41:24 [ INFO] SecureInput has been acquired by 1Password 7, preventing espanso from working correctly. Full path: /Applications/1Password 7.app/Contents/MacOS/1Password 7
07:41:29 [ INFO] SecureInput has been disabled.
07:42:29 [ INFO] SecureInput has been acquired by Netflix, preventing espanso from working correctly. Full path: /Applications/Netflix.app/Contents/MacOS/Flotato
07:42:39 [ INFO] SecureInput has been disabled.
08:54:49 [ INFO] SecureInput has been acquired by Firefox, preventing espanso from working correctly. Full path: /Applications/Firefox.app/Contents/MacOS/firefox
08:54:59 [ INFO] SecureInput has been disabled.
09:01:36 [ INFO] Toggled: espanso disabled
09:10:31 [ INFO] Toggled: espanso enabled
09:34:45 [ INFO] Toggled: espanso disabled
09:46:15 [ INFO] Toggled: espanso enabled
09:48:41 [ INFO] SecureInput has been acquired by Google Chrome, preventing espanso from working correctly. Full path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
09:48:46 [ INFO] SecureInput has been disabled.
19:23:50 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
19:23:55 [ INFO] SecureInput has been disabled.
19:37:58 [ INFO] Toggled: espanso disabled
19:41:53 [ INFO] Toggled: espanso enabled
05:02:39 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
05:02:44 [ INFO] SecureInput has been disabled.
06:10:25 [ INFO] SecureInput has been acquired by Twitter, preventing espanso from working correctly. Full path: /Applications/Twitter.app/Contents/MacOS/Twitter
06:10:30 [ INFO] SecureInput has been disabled.
06:10:45 [ INFO] SecureInput has been acquired by Twitter, preventing espanso from working correctly. Full path: /Applications/Twitter.app/Contents/MacOS/Twitter
06:10:50 [ INFO] SecureInput has been disabled.
06:10:55 [ INFO] SecureInput has been acquired by Twitter, preventing espanso from working correctly. Full path: /Applications/Twitter.app/Contents/MacOS/Twitter
06:11:01 [ INFO] SecureInput has been disabled.
06:11:06 [ INFO] SecureInput has been acquired by Twitter, preventing espanso from working correctly. Full path: /Applications/Twitter.app/Contents/MacOS/Twitter
06:11:11 [ INFO] SecureInput has been disabled.
06:12:16 [ INFO] SecureInput has been acquired by Twitter, preventing espanso from working correctly. Full path: /Applications/Twitter.app/Contents/MacOS/Twitter
06:13:07 [ INFO] SecureInput has been disabled.
10:11:58 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
10:12:03 [ INFO] SecureInput has been disabled.
10:13:09 [ INFO] SecureInput has been acquired by Firefox, preventing espanso from working correctly. Full path: /Applications/Firefox.app/Contents/MacOS/firefox
10:13:14 [ INFO] SecureInput has been disabled.
12:33:22 [ INFO] Toggled: espanso disabled
12:49:20 [ INFO] SecureInput has been acquired by SecurityAgent, preventing espanso from working correctly. Full path: /System/Library/Frameworks/Security.framework/Versions/A/MachServices/SecurityAgent.bundle/Contents/MacOS/SecurityAgent
12:49:25 [ INFO] SecureInput has been disabled.
13:20:52 [ INFO] Toggled: espanso enabled
13:33:00 [ INFO] Toggled: espanso disabled
13:33:08 [ INFO] Toggled: espanso enabled
13:34:27 [ INFO] Toggled: espanso disabled
13:34:58 [ INFO] Toggled: espanso enabled
13:36:29 [ INFO] Toggled: espanso disabled
13:36:42 [ INFO] Toggled: espanso enabled
15:19:41 [ INFO] SecureInput has been acquired by Google Chrome, preventing espanso from working correctly. Full path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
15:19:46 [ INFO] SecureInput has been disabled.
15:29:15 [ INFO] Toggled: espanso disabled
16:27:25 [ INFO] Toggled: espanso enabled
16:39:30 [ INFO] Toggled: espanso disabled
16:56:09 [ INFO] Toggled: espanso enabled
17:19:05 [ INFO] Toggled: espanso disabled
17:19:10 [ INFO] Toggled: espanso enabled
17:19:15 [ INFO] Toggled: espanso disabled
17:19:19 [ INFO] Toggled: espanso enabled
17:22:02 [ INFO] Toggled: espanso disabled
17:22:07 [ INFO] Toggled: espanso enabled
17:22:24 [ INFO] Toggled: espanso disabled
17:23:40 [ INFO] Toggled: espanso enabled
```

**Comment by federico-terzi** [comment] 2021-03-07 18:48
@navxio Thanks! From the logs, I can see that the `SecureInput` mode is enabled multiple times.
Without going too much into details, `SecureInput` is a macOS feature that prevents text expanders from working when interacting with password fields or other "secure" input fields, and there is not much we can do about that...

I'm pretty sure this "randomly disabled" behavior is due to this feature, so I'll close this issue as won't fix. If you don't think this is the cause, feel free to re-open it :)

If you are interested in finding out more, please read this article: https://textexpander.com/secure-input/

**Comment by federico-terzi** [comment] 2021-03-08 11:30
@navxio If you have the chance, could you please see whether the times in the log when you find "Secure Input has been acquired..." matches the times when you find espanso being disabled randomly? (keep in mind that the log times are in UTC rather than your local time, we are working on that issue as well :) )

**Comment by navxio** [comment] 2021-03-09 04:18
@federico-terzi absolutely. Whatever I can do to help :)

**Comment by federico-terzi** [comment] 2021-03-09 14:54
@navxio Thank you :)

**Comment by etiennepellegrini** [comment] 2021-03-19 03:08
I'm allowing myself to comment on this closed issue (let me know if I should start a new one) because I do believe that the behavior of Espanso when SecureInput turns on/off could be improved: while disabling espanso when SecureInput turns on is the desired behavior, espanso seems to "randomly" decide to reload or not after SecureInput is turned off.

Do you think there could be a way to more reliably turn espanso back on? I feel like any time I want to use it these days, it's disabled and I need to `espanso restart`

**Comment by navxio** [comment] 2021-03-31 22:08
@federico-terzi indeed it happens when I use 1password.. but shouldn't espanso restart itself once the secure input lock is removed?

**Comment by federico-terzi** [comment] 2021-04-03 08:47
> indeed it happens when I use 1password.. but shouldn't espanso restart itself once the secure input lock is removed?

I'll try to investigate further on this issue, as many users are experiencing the same thing. The biggest problem is that espanso doesn't disable itself, but it gets disabled by the system instead. If the system decides that secure input is still active (which seems to be the case with 1Password) espanso simply can't work...

**Comment by navxio** [comment] 2021-04-05 09:54
@federico-terzi espanso disables also when disconnected from the internet. This should be checked

**Comment by federico-terzi** [comment] 2021-04-05 17:22
@navxio This is strange! Could you please elaborate more on this issue? Espanso does not depend on the internet (except when installing new packages). Perhaps, it has to do with a 1Password extension on the browser?

**Comment by jraamk** [comment] 2021-04-18 08:16
I am also facing the same issue. Whatever browser we use, it says "SecureInput has been acquired by Google Chrome, preventing espanso from working correctly"

**Comment by richardjlo** [comment] 2021-08-11 22:59
Im seeing the same issue. I use 1Password on Brave

04:12:43 [ INFO] SecureInput has been acquired by SecurityAgent, preventing espanso from working correctly. Full path: /System/Library/Frameworks/Security.framework/Versions/A/MachServices/SecurityAgent.bundle/Contents/MacOS/SecurityAgent
04:14:19 [ INFO] SecureInput has been disabled.
12:00:36 [ INFO] SecureInput has been acquired by SecurityAgent, preventing espanso from working correctly. Full path: /System/Library/Frameworks/Security.framework/Versions/A/MachServices/SecurityAgent.bundle/Contents/MacOS/SecurityAgent
12:00:41 [ INFO] SecureInput has been disabled.
17:02:23 [ INFO] SecureInput has been acquired by Brave Browser, preventing espanso from working correctly. Full path: /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
17:02:28 [ INFO] SecureInput has been disabled.
17:06:51 [ INFO] SecureInput has been acquired by Brave Browser, preventing espanso from working correctly. Full path: /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
17:06:56 [ INFO] SecureInput has been disabled.
20:49:21 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
20:49:46 [ INFO] SecureInput has been disabled.
22:50:27 [ INFO] Toggled: espanso disabled

**Comment by federico-terzi** [comment] 2021-08-12 17:31
@richardjlo Thank you for sharing. The next time this happens, could you please try going over each Brave window and clicking on the "address bar" and see if that helps? (the goal is to try to un-focus the pages)

**Comment by tino** [comment] 2022-09-26 11:57
This might be the same issue, otherwise I can start a new one.

```shell
❯ espanso restart
WARNING: An application is currently using SecureInput and might prevent espanso from working correctly.

APP: loginwindow
PROC: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow

Please close it or disable SecureInput for that application (most apps that use it have a
setting to disable it).
Until then, espanso might not work as expected.
Daemon started correctly!
```

I cannot kill that process (even though I own it...). 

This started to happen more often recently. It works again if I restart my computer.

MacOS: 12.0.1
Espanso: 0.7.3

**Comment by eugenesvk** [comment] 2023-07-13 13:07
By the way, is there some accessibility permission that can override secureinput?

**Comment by smeech** [comment] 2024-02-13 12:54
I suspect this problem may be insoluble with current versions of macOS?

**Closed** 2024-08-17 08:42 UTC
Labels: bug, MacOS
