### ISSUE TITLE
Sometimes  pasting fails and it types V when I try to use on a terminal window

### ISSUE THREAD

**Issue by matheusfillipe** [espanso/espanso#532] opened 2020-11-29 01:07 UTC
Sometimes, not always but usually on the first time i try to use a trigger after focusing a terminal  window that uses ctrl+shift+v, it will just replace my trigger with V (Like if ctrl wasn't being pressed?). Notice that is the first time, using it later on the window won't cause any issue and just works, but there is something about the first time a terminal is focused it seems.

Is there any workaround for this (changing the backend or something I am not aware?)?

OS: Arch Linux x86_64, DE: KDE Plasma 5.20.2, CPU: Intel i7-7700HQ (8) @ 3.800GHz, GPU: NVIDIA GeForce GTX 1050 Ti Mobile, GPU: Intel HD Graphics 630, Memory: 15.5 GiB

**Comment by federico-terzi** [comment] 2020-12-01 19:15
Hey @matheusfillipe,

Thanks for reporting this issue! Does it happen with a specific match?
I'm curious to know whether you press SHIFT or CTRL as part of typing the trigger, as that might explain why it doesn't work (if espanso tries to paste a text, but you still have the modifier down, the shortcut will not work correctly). 

Cheers :)

**Comment by matheusfillipe** [comment] 2020-12-01 21:35
It happens with all matches, but only sure it's happening with ones that begin with `:`.  I also thought I was probably just holding ctrl or shift but that is not the case at all. 

Next time it starts happening again I'll try to find more out but I wasn't able to reproduce it when i want 😅.

**Comment by federico-terzi** [comment] 2020-12-03 18:30
All right, let me know if you discover something else :)

**Comment by matheusfillipe** [comment] 2020-12-22 22:53
Sometimes it also writes V to a normal GUI window, but happens less than with on a terminal window. I am not holding any of the ctrl or shift keys and it simply types "V". 

Also it is always on the first attempt, right after those windows are focused. This never happens again once the window was already used.

**Comment by matheusfillipe** [comment] 2021-01-09 05:41
This is logged when the problem happens.
``` 
07:20:06 [ WARN] X11 reported an error code: 2, request_code: 101 and minor_code: 0
07:20:06 [ WARN] X11 reported an error code: 2, request_code: 101 and minor_code: 0
07:20:06 [ WARN] X11 reported an error code: 2, request_code: 101 and minor_code: 0
07:20:06 [ WARN] X11 reported an error code: 2, request_code: 101 and minor_code: 0
07:20:06 [ WARN] X11 reported an error code: 2, request_code: 101 and minor_code: 0
07:20:06 [ WARN] X11 reported an error code: 2, request_code: 101 and minor_code: 0

```

**Comment by federico-terzi** [comment] 2021-01-10 18:46
@matheusfillipe Interesting, thanks for investigating! Did you notice if that happens also on other applications?

**Comment by matheusfillipe** [comment] 2021-01-11 02:23
Yes it happens for any application actually, just tested and happened here while i type this on firefox. That error isn't always logged though. Nothing was logged now. 

It is always on first times, like after the first time I focus a window, trying now again it works.

**Comment by federico-terzi** [comment] 2021-01-12 19:16
@matheusfillipe Thank you. I suspect there might be a slight incompatibility with Arch. Which installation method did you use?
In case you haven't already, you might try with the `espanso` AUR package: https://espanso.org/install/linux/#installing-on-manjaro--arch

Previously, there was also an `espanso-bin` package, but that was causing problems on Arch systems and so we removed it...

**Comment by matheusfillipe** [comment] 2021-01-12 19:33
Yeah I tried espanso and espanso-bin packages. Have this problem on both. The problem happened but nothing suspicious was logged here:

``` 
$ espanso log  
19:25:28 [ INFO] espanso version 0.7.3
19:25:28 [ INFO] using config path: /home/matheus/.config/espanso
19:25:28 [ INFO] using package path: /home/matheus/.local/share/espanso/packages
19:25:28 [ INFO] spawning worker process...
19:25:28 [ INFO] Binded to IPC unix socket: /home/matheus/.local/share/espanso/espanso.sock
19:25:28 [ INFO] watching for changes in path: /home/matheus/.config/espanso
19:25:28 [ INFO] initializing worker process...
19:25:28 [ INFO] Binded to IPC unix socket: /home/matheus/.local/share/espanso/worker.sock
19:25:28 [ INFO] Using modulo at "/usr/bin/modulo"
19:25:29 [ INFO] worker is running!
19:25:37 [ INFO] Toggled: espanso disabled

```
I am trying espanso-git now and seems to be better. Didn't happen until now.

**Comment by federico-terzi** [comment] 2021-01-12 20:44
@matheusfillipe All right, thank you. I suspect `espanso-git` won't help much, but trying doesn't hurt :)

**Comment by matheusfillipe** [comment] 2021-01-13 22:12
It seems to be better, I mean, it happened less times, but it still happens on espanso-git as well.

**Comment by federico-terzi** [comment] 2021-01-14 19:15
@matheusfillipe I see, thank you for pointing that out. I'll definitely investigate

**Comment by djaffinito** [comment] 2021-03-10 21:32
This happens for me on Mac Big Sur when I use the Clipboard backend. About 25% of the time, it just pastes "v".

**Comment by federico-terzi** [comment] 2021-03-11 12:22
@djaffinito Interesting, thank you for reporting! It might be due to a race condition, we'll see if the new version #594 suffers from this as well

**Comment by ikai2** [comment] 2022-09-19 19:03
@federico-terzi this issue happens with me as well. sometimes espanso pastes v, I'm using espanso on macOS Monterey 12.6

**Comment by karambaq** [comment] 2023-04-27 01:07
Still happens

```
espanso 2.1.8
MacOS Ventura 13.0
```

**Comment by xmalter** [comment] 2023-09-09 03:22
Any updates?

**Comment by smeech** [comment] 2024-02-13 11:13
Most of these problems can be resolved by changing the `backend:` globally or via `force_mode:` for individual triggers, and occasionally with the `X11` options. Have these been fully explored?

**Comment by alexsoyes** [comment] 2024-04-12 19:45
Hey friends :)

I push Espanso in my AI Driven Developers Community and we like Espanso so much!

(Btw we created an entire prompt for devs based repository on the top of it!)

@smeech I do have the same issue on Mac and I tried many things... none of them are working)

`force_mode: clipboard` in individual triggers as well as `backend: clipboard` in the main config file.

Do you have some other clues?

Is there a way to "save" the lost text pasted as "v" in the clipboard btw? (Maybe @federico-terzi knows)

Thank you for you work guys ❤️

**Comment by smeech** [comment] 2024-04-12 20:21
Have you tried increasing [`pre_paste_delay:`](https://espanso.org/docs/configuration/options/)? That's the next option most likely to help for this sort of problem.

**Comment by alexsoyes** [comment] 2024-04-15 05:48
> Have you tried increasing [`pre_paste_delay:`](https://espanso.org/docs/configuration/options/)? That's the next option most likely to help for this sort of problem.

@smeech  I tried to wait for 2 seconds and then... it pasted a `v` ! :'(

**Comment by smeech** [comment] 2024-04-15 09:21
What's are the outputs of `#detect#` and `#acfg#`?

**Comment by alexsoyes** [comment] 2024-04-23 03:17
@smeech :)

> #detect#

```text
title: 'Sometimes pasting fails and it types V when I try to use on a terminal window · Issue #532 · espanso/espanso - Google Chrome – Alex'
exec: '/Applications/Google Chrome.app'
class: 'com.google.Chrome'
```

> #acfg#

```text
[espanso config: "/Users/alexsoyer/Library/Application Support/espanso/config/default.yml"]

backend: Clipboard
enable: true
paste_shortcut: None
inject_delay: None
key_delay: None
apply_patch: true
word_separators: [" ", ",", ".", "?", "!", "\r", "\n", "\u{16}"]

preserve_clipboard: true
clipboard_threshold: 100
disable_x11_fast_inject: false
pre_paste_delay: 100
paste_shortcut_event_delay: 10
toggle_key: None
auto_restart: true
restore_clipboard_delay: 300 
post_form_delay: 200 
post_search_delay: 200 
backspace_limit: 5
search_trigger: None
search_shortcut: Some("ALT+SPACE")
keyboard_layout: None

show_icon: true
show_notifications: true
secure_input_notification: true

x11_use_xclip_backend: false
x11_use_xdotool_backend: false
win32_exclude_orphan_events: true
win32_keyboard_layout_cache_interval: 2000

match_paths: [
    "/Users/alexsoyer/Library/Application Support/espanso/match/packages/ai-driven-dev-prompts/package.yml",
    "/Users/alexsoyer/Library/Application Support/espanso/match/packages/ai-driven-dev-prompts-private/package.yml",
    "/Users/alexsoyer/Projects/text-expander-config/espanso.yml",
]

```

**Comment by smeech** [comment] 2024-04-23 18:31
Just to clarify - @matheusfillipe's problem was in a terminal emulator, but yours is in Chrome?

Do you have the same problem in plain text editors? Which field in Chrome are you trying to type into - the URL/search bar, or a field in a web-page?

Have you tried `disable_x11_fast_inject: true`?

**Comment by alexsoyes** [comment] 2024-04-25 10:11
@smeech , I have the paste `v` issue anywhere, from Chrome to Warp to VSCode, it does not matter 🤷‍♂️ :)

I did not try with x11, I am using OSX so I thought it would not matter, I try right away!

**Comment by alexsoyes** [comment] 2024-05-03 06:27
`disable_x11_fast_inject: true` did not changed anything @smeech , any other clues? :)

**Comment by smeech** [comment] 2024-05-03 09:46
You could try some of the other settings in [Options reference](https://espanso.org/docs/configuration/options/#options-reference), otherwise come and ask on [Discord](https://discord.gg/4QARseMS6k) to see if anyone else has a solution to this problem.

**Closed** 2024-08-17 09:01 UTC
Labels: bug, Linux

**Comment by ddiazepam** [comment] 2024-11-05 10:54
is there any solution? Randomly I get only 'v' pasted and later if i try to backspace that 'v' editor goes crazy and starts to delete everything. Quite frustrating issue @federico-terzi . How can I help to solve it?

**Comment by saurabh-1410** [comment] 2024-11-07 15:06
same, it pasts v then starts deleting everything. very frustrating if you have typed a long reply and then see it all deleted by espanso

**Comment by duda-designer** [comment] 2025-03-27 08:58
I keep getting the same issue on a Mac Big Sur.

Randomly, in multiple apps (Firefox, Notes), it pastes "v" after typing out the trigger.

Afterwards, on pressing the backspace, it acts as if it was pressed constantly and keeps deleting more characters.

The only way to stop it is to hit the Cmd key.

When I press the Cmd key on and off just before typing the last letter of the trigger, it never happens.

Here are my logs:

`09:22:53 [worker(67901)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...`
`09:22:55 [worker(67901)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
`

**Comment by duda-designer** [comment] 2025-03-27 13:27
Update: 

Started using `backend: Inject` for my longer texts and it eliminated the problem so far. It just takes a few seconds to type out, as it's a multilane snippet.

**Comment by rubbbertoee** [comment] 2025-03-30 22:33
> Update:
> 
> Started using `backend: Inject` for my longer texts and it eliminated the problem so far. It just takes a few seconds to type out, as it's a multilane snippet.

I am a total novice with this kind of tech issue. May you expand upon what using "backend: Inject" means? I have the same issue, and I would like to implement this fix. Thanks in advance. MacOS Sonoma

**Comment by duda-designer** [comment] 2025-03-31 09:01
> > Update:
> > Started using `backend: Inject` for my longer texts and it eliminated the problem so far. It just takes a few seconds to type out, as it's a multilane snippet.
> 
> I am a total novice with this kind of tech issue. May you expand upon what using "backend: Inject" means? I have the same issue, and I would like to implement this fix. Thanks in advance. MacOS Sonoma

@rubbbertoee Sure. You'll need to edit your config file.

Open Finder, from the top menu select Go > Go To Folder...

Type in `/Users/[your_username]/Library/Application Support/espanso/`

Find `config/default.yml`

In the file, find the line 27 that starts with `# backend: Inject` and remove the `#` to uncomment the line. Or just add `backend: Inject` anywhere.

**Comment by HaleTom** [comment] 2025-08-30 16:18
The same issue exists in Wezterm on Linux when trying to insert emoji: without `backend: inject`, it's as if Ctrl-V was pressed on the keyboard:

https://www.reddit.com/r/espanso/comments/1n32fl7/expanding_emoji_in_wezterm/

Work-around also therein.

**Comment by mil84** [comment] 2026-05-05 05:52
I have the same issue in every app (Mac OS Tahoe), all the time and dozens times per day (happens anything 10–50% of the times whenever I want to paste something - but impossible to reproduce reliably, it's completely random). 

It's very annoying, is there any fix?
