### ISSUE TITLE
Why can't I work in the Notepad software that comes with Win11?

### ISSUE THREAD

**Issue by zhl111** [espanso/espanso#1481] opened 2022-12-19 17:43 UTC
**Describe the bug**
A clear and concise description of what the bug is
![image](https://user-images.githubusercontent.com/29135984/208486992-3f4fcf9d-d5c3-48a6-af18-466654e7b709.png)

**To Reproduce**
1.

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem
01:33:27 [daemon(23340)] [INFO] reading configs from: "C:\\Users\\on-on\\AppData\\Roaming\\espanso"
01:33:27 [daemon(23340)] [INFO] reading packages from: "C:\\Users\\on-on\\AppData\\Roaming\\espanso\\match\\packages"
01:33:27 [daemon(23340)] [INFO] using runtime dir: "C:\\Users\\on-on\\AppData\\Local\\espanso"
01:33:27 [daemon(23340)] [INFO] system info: Windows v10 (22621) - kernel: 22621
01:33:27 [daemon(23340)] [INFO] watching for changes in path: "C:\\Users\\on-on\\AppData\\Roaming\\espanso"
01:33:27 [daemon(23340)] [INFO] espanso version: 2.1.8
01:33:27 [daemon(23340)] [INFO] spawning the worker process...
01:33:27 [daemon(23340)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
01:33:27 [worker(30392)] [INFO] reading configs from: "C:\\Users\\on-on\\AppData\\Roaming\\espanso"
01:33:27 [worker(30392)] [INFO] reading packages from: "C:\\Users\\on-on\\AppData\\Roaming\\espanso\\match\\packages"
01:33:27 [worker(30392)] [INFO] using runtime dir: "C:\\Users\\on-on\\AppData\\Local\\espanso"
01:33:27 [worker(30392)] [INFO] system info: Windows v10 (22621) - kernel: 22621
01:33:27 [worker(30392)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
01:33:27 [worker(30392)] [INFO] using Win32AppInfoProvider
01:33:27 [worker(30392)] [INFO] monitoring the status of the daemon process
01:33:27 [worker(30392)] [INFO] using Win32Source
01:33:27 [worker(30392)] [INFO] using Win32Injector
01:33:27 [worker(30392)] [INFO] using Win32Clipboard

**Setup information**
- OS: What OS are you using?
  - win11
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)
  - 2.1.8

**Comment by arborrow** [comment] 2023-05-07 10:47
I am running Windows 11 Home and Windows Notepad 11.2303.40.0 with Espanso 2.1.8. I have a shortcut defined that works in Word or Wordpad with some text and the clipboard variable although even removing the clipboard variable I experience the issue in Notepad. 

When I type the trigger or shortcut, the text begins to expand; however, it stops and I have to continue to press enter or do some type of keyboard activity for it to continue. My workaround is simply not to use Notepad. I also tried using Beeftext (another text expander and had a similar issue. I suspect that Notepad is interfering with the normal behavior and that the issue is in notepad. 
Hopefully this helps others who may be experiencing similar issues. I do not believe it is a problem with espanso. I also downloaded Notepad++ and did not have any issues with the same shortcuts.

**Comment by Rhywun** [comment] 2023-06-25 21:56
> the text begins to expand; however, it stops and I have to continue to press enter or do some type of keyboard activity for it to continue.

I have the same issue in Notepad and in fact I thought espanso was broken so I updated from 2.1.7-beta to 2.1.8 and this behavior got _worse_, LOL.

I only use Notepad for quick notes so that was where I was testing some config changes that I had edited in VSCode. When I went back to VSCode to test, my expansions worked normally.

> My workaround is simply not to use Notepad.

Indeed.

**Comment by djlauk** [comment] 2023-12-12 09:09
I installed and tried espanso today and I have the same problem.

Config / versions:
- Windows 11
- notepad (Windows editor) 11.2310.13.0
- espanso 2.1.8.

I figured out a workaround by accident: Once I move the mouse (while over the editor window), everything works as expected.

My _guess_ is, that it needs a UI event being sent (keypress or mouse move) to the editor window in order to proceed processing.

Also: If I mouse click, instead of moving the mouse, it will stop processing the expansion.

**Comment by smeech** [comment] 2024-02-17 16:23
Many of these problems can now be resolved by testing [`force_mode:`](https://espanso.org/docs/matches/basics/#injection-mechanism) for individual triggers (leading to changes in the `backend:` globally or in app-specific configurations), and occasionally with other [options](https://espanso.org/docs/configuration/options/). 
Have you tried those?

**Comment by swaldman3** [comment] 2024-06-30 20:24
I've just encountered the same problem while trying Espanso for the first time. Unless I am messing in up in configuring them, both injection and clipboard modes show the same issue. If I hold a shift key, the injection proceeds slowly but happily; but otherwise, it manages up to two characters and then stops.

**Comment by swaldman3** [comment] 2024-06-30 20:31
I've just started trying Espanso, and have run into this peculiar issue with Win11 notepad. But 
```

filter_exec: Notepad.exe
backend: clipboard
```

fixes it.

**Comment by karlberggren** [comment] 2024-07-14 15:19
Just a note to future readers: these options should go into the `config/default.yml` file in the installation directory

**Closed** 2024-07-14 17:26 UTC
Labels: bug

**Comment by smeech** [comment] 2024-07-14 17:28
Thank you, @swaldman3 and @karlberggren for testing this. 

I'll close this old issue now, if that's OK.
