### ISSUE TITLE
Espanso does not replace text on Macos Monterrey 12.0.1

### ISSUE THREAD

**Issue by pocc** [espanso/espanso#883] opened 2021-11-21 22:21 UTC
### Describe the bug

Espanso is running and does not replace a simple trigger.

### To Reproduce

1. Typing in `;es` does nothing.

2. $ espanso edit

  ```
  matches:
    - trigger: ';es'
      replace: 'espanso'
  ```

3. $ espanso edit default

  ```
  # Automatically generated by espanso migration tool
  # Original file: default.yml
  
  auto_restart: true
  undo_backspace: true
  ```

4. Espanso is running
  
  ```
  $ espanso status
  espanso is running
  ```

* There are no other user yml files.
* There are no logs indicating an error

### Logs
19:58:28 [daemon(500)] [INFO] reading configs from: "/Users/rj/Library/Preferences/espanso"
19:58:28 [daemon(500)] [INFO] reading packages from: "/Users/rj/Library/Application Support/espanso/packages"
19:58:28 [daemon(500)] [INFO] using runtime dir: "/Users/rj/Library/Application Support/espanso"
19:58:28 [daemon(500)] [INFO] watching for changes in path: "/Users/rj/Library/Preferences/espanso"
19:58:28 [daemon(500)] [INFO] espanso version: 2.0.4-alpha
19:58:28 [daemon(500)] [INFO] spawning the worker process...
19:58:28 [daemon(500)] [INFO] binded to IPC unix socket: /Users/rj/Library/Application Support/espanso/espansodaemonv2.sock
19:58:28 [worker(689)] [INFO] reading configs from: "/Users/rj/Library/Preferences/espanso"
19:58:28 [worker(689)] [INFO] reading packages from: "/Users/rj/Library/Application Support/espanso/packages"
19:58:28 [worker(689)] [INFO] using runtime dir: "/Users/rj/Library/Application Support/espanso"
19:58:28 [worker(689)] [INFO] binded to IPC unix socket: /Users/rj/Library/Application Support/espanso/espansoworkerv2.sock
19:58:28 [worker(689)] [INFO] monitoring the status of the daemon process
19:58:28 [worker(689)] [INFO] monitoring the status of secure input
19:58:28 [worker(689)] [INFO] using CocoaAppInfoProvider
19:58:28 [worker(689)] [INFO] using CocoaSource
19:58:28 [worker(689)] [INFO] using MacInjector
19:58:28 [worker(689)] [INFO] using CocoaClipboard
09:48:09 [worker(689)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
09:48:12 [worker(689)] [INFO] secure input has been disabled
11:00:38 [worker(689)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
11:00:40 [worker(689)] [INFO] secure input has been disabled
11:37:12 [worker(689)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
11:37:13 [worker(689)] [INFO] secure input has been disabled
14:12:23 [daemon(500)] [INFO] configuration change detected, restarting worker process...
14:12:23 [worker(689)] [INFO] engine eventloop has terminated, propagating exit event...
14:12:23 [worker(689)] [INFO] waiting for engine exit mode...
14:12:23 [worker(689)] [INFO] exiting worker process...
14:12:23 [daemon(500)] [INFO] spawning the worker process...
14:12:23 [worker(16974)] [INFO] reading configs from: "/Users/rj/Library/Preferences/espanso"
14:12:23 [worker(16974)] [INFO] reading packages from: "/Users/rj/Library/Application Support/espanso/packages"
14:12:23 [worker(16974)] [INFO] using runtime dir: "/Users/rj/Library/Application Support/espanso"
14:12:23 [worker(16974)] [INFO] using CocoaAppInfoProvider
14:12:23 [worker(16974)] [INFO] binded to IPC unix socket: /Users/rj/Library/Application Support/espanso/espansoworkerv2.sock
14:12:23 [worker(16974)] [INFO] using CocoaSource
14:12:23 [worker(16974)] [INFO] monitoring the status of the daemon process
14:12:23 [worker(16974)] [INFO] monitoring the status of secure input
14:12:23 [worker(16974)] [INFO] using MacInjector
14:12:23 [worker(16974)] [INFO] using CocoaClipboard
14:12:53 [daemon(500)] [INFO] configuration change detected, restarting worker process...
14:12:53 [worker(16974)] [INFO] engine eventloop has terminated, propagating exit event...
14:12:53 [worker(16974)] [INFO] waiting for engine exit mode...
14:12:53 [worker(16974)] [INFO] exiting worker process...
14:12:53 [daemon(500)] [INFO] spawning the worker process...
14:12:53 [worker(16981)] [INFO] reading configs from: "/Users/rj/Library/Preferences/espanso"
14:12:53 [worker(16981)] [INFO] reading packages from: "/Users/rj/Library/Application Support/espanso/packages"
14:12:53 [worker(16981)] [INFO] using runtime dir: "/Users/rj/Library/Application Support/espanso"
14:12:53 [worker(16981)] [INFO] using CocoaAppInfoProvider
14:12:53 [worker(16981)] [INFO] binded to IPC unix socket: /Users/rj/Library/Application Support/espanso/espansoworkerv2.sock
14:12:53 [worker(16981)] [INFO] using CocoaSource
14:12:53 [worker(16981)] [INFO] monitoring the status of the daemon process
14:12:53 [worker(16981)] [INFO] monitoring the status of secure input
14:12:53 [worker(16981)] [INFO] using MacInjector
14:12:53 [worker(16981)] [INFO] using CocoaClipboard
14:13:16 [service(16985)] [INFO] reading configs from: "/Users/rj/Library/Preferences/espanso"
14:13:16 [service(16985)] [INFO] reading packages from: "/Users/rj/Library/Application Support/espanso/packages"
14:13:16 [service(16985)] [INFO] using runtime dir: "/Users/rj/Library/Application Support/espanso"
14:13:16 [service(16985)] [INFO] espanso is running

### Setup information
$ espanso --version
espanso 2.0.4-alpha

Macos 12.0.1

---

Aside: Change the bug report text to use h2 or h3s instead of bold for readability

**Comment by federico-terzi** [comment] 2021-11-22 20:00
Hey @pocc,

Thanks for reporting this issue! A couple of questions:
* Could you please try opening the Accessibility settings (System Preferences > Security & Privacy > Privacy > Accessibility) and then uncheck and re-check Espanso in the list
* Does it happen with all snippets or only with `;es`?
* Could you please post a screenshot of the icon you see in the status bar?

Thanks for your help :)

**Comment by pocc** [comment] 2021-12-03 04:14
I wanted to isolate this issue, so ;es is the only trigger.

![image](https://user-images.githubusercontent.com/10995145/144544096-98750b4c-d90d-4330-84d8-97ef968c9e93.png)

For some reason macos won't let me toggle it off/on.

![image](https://user-images.githubusercontent.com/10995145/144544133-940c1e2d-ef96-4724-b3d9-cc520ad05f5a.png)

**Comment by glgoose** [comment] 2021-12-03 11:50
I just upgraded to Monterrey v12.0.1 and am experiencing the same issue. It worked on the previous macOS version.

Info:
* espanso v0.7.3
* installed via homebrow at `/opt/homebrew/bin/espanso`

What I tried:
* unchecking & rechecking `espanso` under Accessibility (Security)
![image](https://user-images.githubusercontent.com/48956933/144597593-c5523439-08f2-4a12-b492-98f3629c5ab4.png)

## Status bar
When I restart espanso with `espanso restart` it is disabled by default but then there seems to be a bug because it says `Disable` and should say `Enable` because it's currently disabled.
![image](https://user-images.githubusercontent.com/48956933/144597783-7701d260-dc17-464d-85c5-ce0f92181be7.png)

When I click 'Disable' and then 'Enable' it shows up properly:
![image](https://user-images.githubusercontent.com/48956933/144597297-7235e5e7-11ca-438c-a24e-ac330a99a572.png)

**Comment by federico-terzi** [comment] 2021-12-03 13:49
@pocc thank you! Could you please try:

* Stopping espanso
* Opening the accessibility preference page
* Removing all Espanso entries (with the minus button)
* Relaunching Espanso by double-clicking the App bundle
* Complete the Accessibility setup

and see if that helps? :)

@glgoose Interesting, thanks! When you have the chance, I'd suggest upgrading to the new version, which should solve many of these issues :) https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

**Comment by pocc** [comment] 2021-12-03 15:49
I have done as you've asked. It seems that espanso on 12.0.1 isn't detecting whether it has the accessibility access that it needs, because when double-clicking on the app, it just prompts me to type :espanso, which does nothing anyway.

**Comment by pocc** [comment] 2021-12-03 15:56
So I deleted all of my espanso yml files, and now it works. 

There's a weird behavior that I've noticed. It seems like my problem is related to the trigger `;es`. If you delete all of your yml files on 12.0.1, paste this into base.yml (and espanso automatically reloads), `;es` does nothing. After typing `:espanso`, then `;es` starts working.

```
matches:
  - trigger: ";es"
    replace: "espanso is working"
  - trigger: ":espanso"
    replace: "espanso is working"
```

**Comment by federico-terzi** [comment] 2021-12-04 09:37
@pocc Thank you for sharing your findings! 

>  If you delete all of your yml files on 12.0.1, paste this into base.yml (and espanso automatically reloads), ;es does nothing. After typing :espanso, then ;es starts working.

I'm wondering if that is interfering with macOS built-in text replacement (do you have any text replacements defined on your macOS preferences?) or something related to secure input...

If you have the chance, could you please post the output of `espanso log` here after a failed attempt to expand `;es`?

Thanks for your help :)

**Comment by pocc** [comment] 2021-12-04 15:49
This is reproducible

1. Delete all espanso files
2. `espanso restart`
3. `espanso edit`, add the above config
4. After saving, type `;es` (nothing happens)
5. Type `:espanso` => expands to `espanso is working`
6. Type `;es` => expands to `espanso is working`

`espanso log` provides this output after doing so:

```
07:46:30 [daemon(64455)] [INFO] reading configs from: "/Users/rj/Library/Preferences/espanso"
07:46:30 [daemon(64455)] [INFO] reading packages from: "/Users/rj/Library/Application Support/espanso/packages"
07:46:30 [daemon(64455)] [INFO] using runtime dir: "/Users/rj/Library/Application Support/espanso"
07:46:30 [daemon(64455)] [INFO] espanso version: 2.1.0-alpha
07:46:30 [daemon(64455)] [INFO] spawning the worker process...
07:46:30 [daemon(64455)] [INFO] watching for changes in path: "/Users/rj/Library/Preferences/espanso"
07:46:30 [daemon(64455)] [INFO] binded to IPC unix socket: /Users/rj/Library/Application Support/espanso/espansodaemonv2.sock
07:46:30 [worker(64456)] [INFO] reading configs from: "/Users/rj/Library/Preferences/espanso"
07:46:30 [worker(64456)] [INFO] reading packages from: "/Users/rj/Library/Application Support/espanso/packages"
07:46:30 [worker(64456)] [INFO] using runtime dir: "/Users/rj/Library/Application Support/espanso"
07:46:30 [worker(64456)] [INFO] using CocoaAppInfoProvider
07:46:30 [worker(64456)] [INFO] binded to IPC unix socket: /Users/rj/Library/Application Support/espanso/espansoworkerv2.sock
07:46:30 [worker(64456)] [INFO] using CocoaSource
07:46:30 [worker(64456)] [INFO] monitoring the status of the daemon process
07:46:30 [worker(64456)] [INFO] monitoring the status of secure input
07:46:30 [worker(64456)] [INFO] using MacInjector
07:46:30 [worker(64456)] [INFO] using CocoaClipboard
07:46:49 [daemon(64455)] [INFO] configuration change detected, restarting worker process...
07:46:49 [worker(64456)] [INFO] engine eventloop has terminated, propagating exit event...
07:46:49 [worker(64456)] [INFO] waiting for engine exit mode...
07:46:49 [worker(64456)] [INFO] exiting worker process...
07:46:49 [daemon(64455)] [INFO] spawning the worker process...
07:46:49 [worker(64481)] [INFO] reading configs from: "/Users/rj/Library/Preferences/espanso"
07:46:49 [worker(64481)] [INFO] reading packages from: "/Users/rj/Library/Application Support/espanso/packages"
07:46:49 [worker(64481)] [INFO] using runtime dir: "/Users/rj/Library/Application Support/espanso"
07:46:49 [worker(64481)] [INFO] using CocoaAppInfoProvider
07:46:49 [worker(64481)] [INFO] binded to IPC unix socket: /Users/rj/Library/Application Support/espanso/espansoworkerv2.sock
07:46:49 [worker(64481)] [INFO] using CocoaSource
07:46:49 [worker(64481)] [INFO] monitoring the status of secure input
07:46:49 [worker(64481)] [INFO] monitoring the status of the daemon process
07:46:49 [worker(64481)] [INFO] using MacInjector
07:46:49 [worker(64481)] [INFO] using CocoaClipboard
```

**Comment by federico-terzi** [comment] 2021-12-05 21:18
@pocc Thanks! This sounds interesting. I'll investigate and get back to you if I discover something :)

I'm wondering if it could be related to `espanso edit`...

**Comment by glgoose** [comment] 2021-12-06 11:12
> @glgoose Interesting, thanks! When you have the chance, I'd suggest upgrading to the new version, which should solve many of these issues :) [#594 (comment)](https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339)

@federico-terzi I installed `2.1.0-alpha` via the download link on the webpage and uninstalled  v0.7.3` that I had installed via homebrew. I can confirm it works now.

I did have an issue with Secure Input but logging out (not simply locking screen) made it work.
Via the script provided by this article [Finding the app/process that’s using Secure Input – alexwlchan](https://alexwlchan.net/2021/04/secure-input/) I found that the process `loginmanager` was keeping Secure Input enabled and logging out killed that process.

I wasn't aware there was a beta, homebrew told me I had the latest version. Homebrew seems to follow the releases tags so it correctly mentioned it was using the `latest` version but the `pre-release` builds were not in there.

So the new v2 espanso cannot be installed via homebrew?

**Comment by federico-terzi** [comment] 2021-12-06 21:14
@glgoose Thanks! 

> So the new v2 espanso cannot be installed via homebrew?

Not currently, but we are planning to bring back support #897. Until then, the App bundle will be the recommended approach :)

**Comment by mgiugliano** [comment] 2022-02-21 15:49
I have the same issue. Finally I noticed the following line in the logs:

15:33:46 [ INFO] SecureInput has been acquired by Slack, preventing espanso from working correctly. Full path: /Applications/Slack.app/Contents/MacOS/Slack

and restarting gave the following clear(er) message:

WARNING: An application is currently using SecureInput and might prevent espanso from working correctly.

APP: Slack
PROC: /Applications/Slack.app/Contents/MacOS/Slack

Please close it or disable SecureInput for that application (most apps that use it have a setting to disable it).
Until then, espanso might not work as expected.
Daemon started correctly!


I could NOT find a way to change Slack's "SecureInput" behavior/setting. However, even after closing Slack (and restarting espanso), espanso is still NOT working.

**Comment by federico-terzi** [comment] 2022-02-23 20:01
Hey @mgiugliano,

I'm sorry you experienced this problem! When you have the chance, you could try upgrading to the v2 (see https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339) and then following these steps: https://espanso.org/docs/next/troubleshooting/secure-input/

Cheers :)

**Comment by mgiugliano** [comment] 2022-02-23 21:35
@federico-terzi Thank you! Just upgrading solved my issue. 

I have noticed that changing and reloading the base.yml reproducibly crashes the app :-(
I will open an issue, hoping to provide you with useful information.

Thank you for "espanso", which I only recently discovered and I am still exploring for all its power.

**Comment by 0x3333** [comment] 2022-03-14 18:44
Same issue here, is there anything I can do to help?

```
espanso log
15:41:41 [daemon(12974)] [INFO] reading configs from: "/Users/redacted/Library/Preferences/espanso"
15:41:41 [daemon(12974)] [INFO] reading packages from: "/Users/redacted/Library/Preferences/espanso/match/packages"
15:41:41 [daemon(12974)] [INFO] using runtime dir: "/Users/redacted/Library/Application Support/espanso"
15:41:41 [daemon(12974)] [INFO] espanso version: 2.1.3-alpha
15:41:41 [daemon(12974)] [INFO] spawning the worker process...
15:41:41 [daemon(12974)] [INFO] watching for changes in path: "/Users/redacted/Library/Preferences/espanso"
15:41:41 [daemon(12974)] [INFO] binded to IPC unix socket: /Users/redacted/Library/Application Support/espanso/espansodaemonv2.sock
15:41:41 [worker(12975)] [INFO] reading configs from: "/Users/redacted/Library/Preferences/espanso"
15:41:41 [worker(12975)] [INFO] reading packages from: "/Users/redacted/Library/Preferences/espanso/match/packages"
15:41:41 [worker(12975)] [INFO] using runtime dir: "/Users/redacted/Library/Application Support/espanso"
15:41:41 [worker(12975)] [INFO] using CocoaAppInfoProvider
15:41:41 [worker(12975)] [INFO] binded to IPC unix socket: /Users/redacted/Library/Application Support/espanso/espansoworkerv2.sock
15:41:41 [worker(12975)] [INFO] using CocoaSource
15:41:41 [worker(12975)] [INFO] monitoring the status of the daemon process
15:41:41 [worker(12975)] [INFO] monitoring the status of secure input
15:41:41 [worker(12975)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
15:41:41 [worker(12975)] [INFO] using MacInjector
15:41:41 [worker(12975)] [INFO] using CocoaClipboard
```

**Comment by 0x3333** [comment] 2022-03-16 20:37
@federico-terzi , In my case it was Microsoft Outlook that was holding the secure input. I just closed it and fixed it for me. I was asking if I can do anything to help, but as I read about this issue, it is kind of widespread in MacOS.

**Comment by mgiugliano** [comment] 2022-03-21 21:22
@federico-terzi After upgrading to Monterey 12.3 (21E230), (home-brew installed) espanso 2.1.4-beta stopped working.

Restarting the computer, > espanso start, > espanso restart, unclicking & clicking on System Preferences --> Privacy --> Accessibility "Espanso", did not help.

No information on the system logs and no sign (pin espanso tray icon) that the "Secure Input" is the culprit as it was earlier.
I am happy to help debugging the issue, if needed, sharing my screen on Zoom.

**Comment by federico-terzi** [comment] 2022-03-23 19:54
@mgiugliano Sorry to hear that! You seem to have done everything right. Could you please try uninstalling Espanso, removing the Espanso accessibility entry and then repeating the process from the start?

**Comment by mgiugliano** [comment] 2022-03-24 07:59
> @mgiugliano Sorry to hear that! You seem to have done everything right. Could you please try uninstalling Espanso, removing the Espanso accessibility entry and then repeating the process from the start?

It worked, but for some strange reason I had to reload a couple of times the "config". Mysterious macOs.
Thank you and apologies for having bothered you with a test I could and should have done immediately by myself. :-)

**Comment by alpineyahoo** [comment] 2022-04-15 05:29
didn't work for me...
This dialog below shows up in the espanso log. What does this mean?

`[WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...`

Do you think this has something to do with espanso behaviour?

**Comment by federico-terzi** [comment] 2022-04-19 19:13
@alpineyahoo Unfortunately, It's unlikely to be related... To be honest, I don't have any other idea :( We'll update the issue if something comes up

**Comment by smeech** [comment] 2024-02-13 15:22
I hope this is now resolved so I'll close it for now, as it's a rather old thread. I'm happy to reopen it if the problem persists.

**Closed by smeech** 2024-02-13 15:22 UTC
Labels: bug, MacOS
