### ISSUE TITLE
Swapping of upper/lower case expansiosn

### ISSUE THREAD

**Issue by mattnolan001** [espanso/espanso#1518] opened 2023-02-07 20:40 UTC
**Describe the bug**
Using Espanso when typing in Evolution (3.44.4 on Ubuntu 20.04.1) I find that it often changes the capitalisation of words. For example, when the first letter of a word should be upper case Espanso will expand the word with the first letter as lower case. This happens with triggers that are more than two symbols long (e.g. :espanso), but not with two symbol triggers (e.g. :e). I rarely see the same behaviour using Espanso in Emacs.

**To Reproduce**
Three consecutive expansions after typing ':espanso'
hi THEre1
hi tHEre1
hi There1

**Expected behavior**
I expect ':espanso' to expand to 'Hi there!'

Have tried following suggestions at https://github.com/espanso/espanso/issues/248. This looks different to the issue reported there but is the closest I could find.

**Logs**
20:36:10 [daemon(1145493)] [INFO] reading configs from: "/home/matt/.config/espanso"
20:36:10 [daemon(1145493)] [INFO] reading packages from: "/home/matt/.local/share/espanso/packages"
20:36:10 [daemon(1145493)] [INFO] using runtime dir: "/home/matt/.local/share/espanso"
20:36:10 [daemon(1145493)] [INFO] system info: Ubuntu v22.04 - kernel: 5.15.0-58-generic
20:36:10 [daemon(1145493)] [INFO] watching for changes in path: "/home/matt/.config/espanso"
20:36:10 [daemon(1145493)] [INFO] espanso version: 2.1.8
20:36:10 [daemon(1145493)] [INFO] spawning the worker process...
20:36:10 [daemon(1145493)] [INFO] binded to IPC unix socket: /home/matt/.local/share/espanso/espansodaemonv2.sock
20:36:10 [worker(1145500)] [INFO] reading configs from: "/home/matt/.config/espanso"
20:36:10 [worker(1145500)] [INFO] reading packages from: "/home/matt/.local/share/espanso/packages"
20:36:10 [worker(1145500)] [INFO] using runtime dir: "/home/matt/.local/share/espanso"
20:36:10 [worker(1145500)] [INFO] system info: Ubuntu v22.04 - kernel: 5.15.0-58-generic
20:36:10 [worker(1145500)] [INFO] binded to IPC unix socket: /home/matt/.local/share/espanso/espansoworkerv2.sock
20:36:10 [worker(1145500)] [INFO] using WaylandAppInfoProvider
20:36:10 [worker(1145500)] [INFO] monitoring the status of the daemon process
20:36:10 [worker(1145500)] [INFO] detection module will use this keyboard layout: [R=, M=, L=gb, V=, O=]
20:36:10 [worker(1145500)] [INFO] using EVDEVSource
20:36:11 [worker(1145500)] [INFO] Querying modifier status...
20:36:11 [worker(1145500)] [INFO] inject module will use this keyboard layout: [R=, M=, L=gb, V=, O=]
20:36:11 [worker(1145500)] [INFO] using EVDEVInjector
20:36:11 [worker(1145500)] [INFO] using WaylandFallbackClipboard

**Setup information**
- OS: Ubuntu 20.04.1
- Version: 2.1.8

**Comment by Vistaus** [comment] 2023-07-12 11:18
Are you still experiencing this issue? I can't reproduce this on openSUSE Tumbleweed with the latest Espanso git dev branch.

Also, Ubuntu 20.04 or 22.04? Because you wrote 20.04, but the Espanso output shows 22.04.

**Comment by mattnolan001** [comment] 2023-07-14 19:41
22.04

I played around with the injection delay settings and have it working ok now,

**Comment by Vistaus** [comment] 2023-07-14 20:18
That's great to hear! I think that's the best you can do about it as there are so many different variables on each system that can play into this, so I think it's best to close this issue. But I'm glad to hear it's working OK for you now! 🙂

**Closed** 2024-02-17 17:45 UTC
Labels: bug
