### ISSUE TITLE
Incorrect position of fill in case of multiple screens

### ISSUE THREAD

**Issue by 17307** [espanso/espanso#1547] opened 2023-03-16 01:46 UTC
**Describe the bug**
When I use multiple screens, both screens have vscode windows open at the same time, and then a command is executed that requires a form form to be filled, at which point the form form pops up on the non-cursor window, and when the input is complete, the output fills in the vscode in the wrong window.

**suggestion**
It would be nice if the pop-up form box and search box could follow the cursor!

**Setup information**
- OS: Macos
- espanso 2.1.8

**Comment by smeech** [comment] 2024-02-17 18:40
Duplicate of #1497 and possibly #1459

**Closed by smeech** 2024-02-17 18:40 UTC
Labels: bug
