### ISSUE TITLE
Holding Shift key delays match

### ISSUE THREAD

**Issue by Cee1232** [espanso/espanso#1405] opened 2022-10-12 23:40 UTC
Holding either shift key during the final keystroke of a trigger delays the match until the shift key is released.

**To Reproduce**
     -trigger: "abc~" 
     replace: "ABC"

1. Type abc~ and continue holding the shift key. The match will not occur until the shift key is released.
2. If one or more keystrokes occur once the trigger is typed, while the shift key is held (ie: abc~X), the replacement is offset (output is: 'aABC' rather then 'ABCX').

In previous versions the match occurred instantly regardless of shift key status & thus no delays/offset errors were introduced.

Setup: Win 10 Pro / 2.1.7beta

**Comment by ada4a** [comment] 2024-01-02 14:26
Same problem on Linux Mint 21.2 Cinnamon

**Comment by smeech** [comment] 2024-04-04 15:45
Duplicate of #399, with longer discussion there.

**Closed by smeech** 2024-04-04 15:45 UTC
Labels: bug
